// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: suki/pb/em_coding/database/data.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Contains the actual EM code data and associated information
struct Suki_Pb_EmCoding_Database_EMCodeData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of modifiers that can be applied to the code
  var modifiers: [String] = []

  /// Additional codes that can be billed with the primary code
  var addOns: [String] = []

  /// The level of service
  var level: UInt32 = 0

  /// Features used to determine the EM code (either time-based or MDM-based)
  var feature: Suki_Pb_EmCoding_Database_EMCodeData.OneOf_Feature? = nil

  /// Time-based features if the code was determined using time
  var timeBasedFeatures: Suki_Pb_EmCoding_TimeBasedFeatures {
    get {
      if case .timeBasedFeatures(let v)? = feature {return v}
      return Suki_Pb_EmCoding_TimeBasedFeatures()
    }
    set {feature = .timeBasedFeatures(newValue)}
  }

  /// MDM-based features if the code was determined using medical decision making
  var mdmBasedFeatures: Suki_Pb_EmCoding_MDMBasedFeatures {
    get {
      if case .mdmBasedFeatures(let v)? = feature {return v}
      return Suki_Pb_EmCoding_MDMBasedFeatures()
    }
    set {feature = .mdmBasedFeatures(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Features used to determine the EM code (either time-based or MDM-based)
  enum OneOf_Feature: Equatable, Sendable {
    /// Time-based features if the code was determined using time
    case timeBasedFeatures(Suki_Pb_EmCoding_TimeBasedFeatures)
    /// MDM-based features if the code was determined using medical decision making
    case mdmBasedFeatures(Suki_Pb_EmCoding_MDMBasedFeatures)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "suki.pb.em_coding.database"

extension Suki_Pb_EmCoding_Database_EMCodeData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EMCodeData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "modifiers"),
    2: .standard(proto: "add_ons"),
    3: .same(proto: "level"),
    4: .standard(proto: "time_based_features"),
    5: .standard(proto: "mdm_based_features"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.modifiers) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.addOns) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.level) }()
      case 4: try {
        var v: Suki_Pb_EmCoding_TimeBasedFeatures?
        var hadOneofValue = false
        if let current = self.feature {
          hadOneofValue = true
          if case .timeBasedFeatures(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.feature = .timeBasedFeatures(v)
        }
      }()
      case 5: try {
        var v: Suki_Pb_EmCoding_MDMBasedFeatures?
        var hadOneofValue = false
        if let current = self.feature {
          hadOneofValue = true
          if case .mdmBasedFeatures(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.feature = .mdmBasedFeatures(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.modifiers.isEmpty {
      try visitor.visitRepeatedStringField(value: self.modifiers, fieldNumber: 1)
    }
    if !self.addOns.isEmpty {
      try visitor.visitRepeatedStringField(value: self.addOns, fieldNumber: 2)
    }
    if self.level != 0 {
      try visitor.visitSingularUInt32Field(value: self.level, fieldNumber: 3)
    }
    switch self.feature {
    case .timeBasedFeatures?: try {
      guard case .timeBasedFeatures(let v)? = self.feature else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .mdmBasedFeatures?: try {
      guard case .mdmBasedFeatures(let v)? = self.feature else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_EmCoding_Database_EMCodeData, rhs: Suki_Pb_EmCoding_Database_EMCodeData) -> Bool {
    if lhs.modifiers != rhs.modifiers {return false}
    if lhs.addOns != rhs.addOns {return false}
    if lhs.level != rhs.level {return false}
    if lhs.feature != rhs.feature {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
