// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: learningmotors/pb/ie/def.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// This file defines the common structures to be used by all Intent Extractors. It serves as template for
/// any inputs and outputs defined

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Request defines the input to an intent extractor
struct Learningmotors_Pb_Ie_Request {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the IE request
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// Context of the current screen the UI is in
  /// TODO: Change the 'Context' protobuf to UIContext so we don't confuse it
  var uiContext: Learningmotors_Pb_Context {
    get {return _uiContext ?? Learningmotors_Pb_Context()}
    set {_uiContext = newValue}
  }
  /// Returns true if `uiContext` has been explicitly set.
  var hasUiContext: Bool {return self._uiContext != nil}
  /// Clears the value of `uiContext`. Subsequent reads from it will return its default value.
  mutating func clearUiContext() {self._uiContext = nil}

  /// Utterance for which we need to do intent extraction
  var input: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
  fileprivate var _uiContext: Learningmotors_Pb_Context? = nil
}

/// Output defines the output that comes out of an intent extractor
struct Learningmotors_Pb_Ie_Response {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of intents (possibly empty) that the algorithm returns
  var intents: [Learningmotors_Pb_Idl_Intent] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "learningmotors.pb.ie"

extension Learningmotors_Pb_Ie_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Request"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    3: .standard(proto: "ui_context"),
    2: .same(proto: "input"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeSingularStringField(value: &self.input)
      case 3: try decoder.decodeSingularMessageField(value: &self._uiContext)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.input.isEmpty {
      try visitor.visitSingularStringField(value: self.input, fieldNumber: 2)
    }
    if let v = self._uiContext {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Ie_Request, rhs: Learningmotors_Pb_Ie_Request) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs._uiContext != rhs._uiContext {return false}
    if lhs.input != rhs.input {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Ie_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Response"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "intents"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.intents)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.intents.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.intents, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Ie_Response, rhs: Learningmotors_Pb_Ie_Response) -> Bool {
    if lhs.intents != rhs.intents {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
