// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: suki/pb/ssp/v1/resource.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A signal that clients can send to indicate a processing step or a change.enum
/// SSP responds to these signals with a Response or Error signal.
nonisolated enum Suki_Pb_Ssp_V1_RequestSignals: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecifiedRequestSignal // = 0

  /// Pauses speech
  case speechPause // = 1

  /// Resumes speech with the configuration of the session
  case speechResume // = 2

  /// Deprecated as per Buffering Design: https://sukiai.atlassian.net/wiki/spaces/EN/pages/3243114530/Buffering+Implementation+LLD
  ///
  /// NOTE: This enum value was marked as deprecated in the .proto file
  case speechAbort // = 3
  case speechEnd // = 50

  /// Indicates that a command will be sent so that the ASR can trigger faster finalization logic, if supported.
  case commandCue // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecifiedRequestSignal
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecifiedRequestSignal
    case 1: self = .speechPause
    case 2: self = .speechResume
    case 3: self = .speechAbort
    case 4: self = .commandCue
    case 50: self = .speechEnd
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecifiedRequestSignal: return 0
    case .speechPause: return 1
    case .speechResume: return 2
    case .speechAbort: return 3
    case .commandCue: return 4
    case .speechEnd: return 50
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Suki_Pb_Ssp_V1_RequestSignals] = [
    .unspecifiedRequestSignal,
    .speechPause,
    .speechResume,
    .speechAbort,
    .speechEnd,
    .commandCue,
  ]

}

/// A signal from SSP about the state of operation or signal requested.
nonisolated enum Suki_Pb_Ssp_V1_ResponseSignals: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecifiedResponseSignal // = 0
  case endOfUtterance // = 1
  case keepAlive // = 2
  case speechProcessed // = 3
  case speechConfigChanged // = 4
  case speechPaused // = 5
  case speechResumed // = 6

  /// NOTE: This enum value was marked as deprecated in the .proto file
  case speechAborted // = 7
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecifiedResponseSignal
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecifiedResponseSignal
    case 1: self = .endOfUtterance
    case 2: self = .keepAlive
    case 3: self = .speechProcessed
    case 4: self = .speechConfigChanged
    case 5: self = .speechPaused
    case 6: self = .speechResumed
    case 7: self = .speechAborted
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecifiedResponseSignal: return 0
    case .endOfUtterance: return 1
    case .keepAlive: return 2
    case .speechProcessed: return 3
    case .speechConfigChanged: return 4
    case .speechPaused: return 5
    case .speechResumed: return 6
    case .speechAborted: return 7
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Suki_Pb_Ssp_V1_ResponseSignals] = [
    .unspecifiedResponseSignal,
    .endOfUtterance,
    .keepAlive,
    .speechProcessed,
    .speechConfigChanged,
    .speechPaused,
    .speechResumed,
    .speechAborted,
  ]

}

/// Error scenarios that SSP popularly recognizes. These are encoded so that
/// clients can institute their own handling for the same and for informational
/// purposes also. gRPC errors are quite comprehensive in themselves.
nonisolated enum Suki_Pb_Ssp_V1_ErrorSignals: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecifiedErrorSignal // = 0
  case speechConfigError // = 1
  case unsupportedRequest // = 2
  case insufficientPermissions // = 3
  case invalidToken // = 4
  case authenticationError // = 5
  case generalError // = 50
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecifiedErrorSignal
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecifiedErrorSignal
    case 1: self = .speechConfigError
    case 2: self = .unsupportedRequest
    case 3: self = .insufficientPermissions
    case 4: self = .invalidToken
    case 5: self = .authenticationError
    case 50: self = .generalError
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecifiedErrorSignal: return 0
    case .speechConfigError: return 1
    case .unsupportedRequest: return 2
    case .insufficientPermissions: return 3
    case .invalidToken: return 4
    case .authenticationError: return 5
    case .generalError: return 50
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Suki_Pb_Ssp_V1_ErrorSignals] = [
    .unspecifiedErrorSignal,
    .speechConfigError,
    .unsupportedRequest,
    .insufficientPermissions,
    .invalidToken,
    .authenticationError,
    .generalError,
  ]

}

/// Types of audio encoding supported by SSP
nonisolated enum Suki_Pb_Ssp_V1_AudioEncoding: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecifiedEncoding // = 0
  case linear16 // = 1
  static let pcm16Khz = linear16
  case oggOpus // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecifiedEncoding
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecifiedEncoding
    case 1: self = .linear16
    case 2: self = .oggOpus
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecifiedEncoding: return 0
    case .linear16: return 1
    case .oggOpus: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Suki_Pb_Ssp_V1_AudioEncoding] = [
    .unspecifiedEncoding,
    .linear16,
    .oggOpus,
  ]

}

/// Types of Services provided by SSP
nonisolated enum Suki_Pb_Ssp_V1_ServiceType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unknownService // = 0
  case transcription // = 1
  case ambient // = 2
  case qna // = 3
  case iusf // = 4
  case formFilling // = 5
  case codeGeneration // = 6
  case UNRECOGNIZED(Int)

  init() {
    self = .unknownService
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknownService
    case 1: self = .transcription
    case 2: self = .ambient
    case 3: self = .qna
    case 4: self = .iusf
    case 5: self = .formFilling
    case 6: self = .codeGeneration
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unknownService: return 0
    case .transcription: return 1
    case .ambient: return 2
    case .qna: return 3
    case .iusf: return 4
    case .formFilling: return 5
    case .codeGeneration: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Suki_Pb_Ssp_V1_ServiceType] = [
    .unknownService,
    .transcription,
    .ambient,
    .qna,
    .iusf,
    .formFilling,
    .codeGeneration,
  ]

}

/// Status Of QnA Response
nonisolated enum Suki_Pb_Ssp_V1_AnswerStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unknownStatus // = 0
  case answerFound // = 1
  case noAnswerFound // = 2
  case queryNotSupported // = 3
  case errorOccurred // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .unknownStatus
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknownStatus
    case 1: self = .answerFound
    case 2: self = .noAnswerFound
    case 3: self = .queryNotSupported
    case 4: self = .errorOccurred
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unknownStatus: return 0
    case .answerFound: return 1
    case .noAnswerFound: return 2
    case .queryNotSupported: return 3
    case .errorOccurred: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Suki_Pb_Ssp_V1_AnswerStatus] = [
    .unknownStatus,
    .answerFound,
    .noAnswerFound,
    .queryNotSupported,
    .errorOccurred,
  ]

}

/// Language that ASR can transcribe to. Must match the items mentioned in the
/// admin preferences
nonisolated enum Suki_Pb_Ssp_V1_LANGUAGE: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case `default` // = 0
  case english // = 1
  case multilingual // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .default
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .default
    case 1: self = .english
    case 2: self = .multilingual
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .default: return 0
    case .english: return 1
    case .multilingual: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Suki_Pb_Ssp_V1_LANGUAGE] = [
    .default,
    .english,
    .multilingual,
  ]

}

/// Type of ASR used for transcription
nonisolated enum Suki_Pb_Ssp_V1_ASR: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// This is a special case where the platform will use the default
  case `default` // = 0

  /// ASR for the tenant from configuration
  case suki // = 1
  case google // = 2
  case sukiV2 // = 4
  case nvoq // = 5
  case sukiV4 // = 6
  case sukiV5 // = 7
  case sukiV6 // = 8
  case sukiV7 // = 9
  case UNRECOGNIZED(Int)

  init() {
    self = .default
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .default
    case 1: self = .suki
    case 2: self = .google
    case 4: self = .sukiV2
    case 5: self = .nvoq
    case 6: self = .sukiV4
    case 7: self = .sukiV5
    case 8: self = .sukiV6
    case 9: self = .sukiV7
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .default: return 0
    case .suki: return 1
    case .google: return 2
    case .sukiV2: return 4
    case .nvoq: return 5
    case .sukiV4: return 6
    case .sukiV5: return 7
    case .sukiV6: return 8
    case .sukiV7: return 9
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Suki_Pb_Ssp_V1_ASR] = [
    .default,
    .suki,
    .google,
    .sukiV2,
    .nvoq,
    .sukiV4,
    .sukiV5,
    .sukiV6,
    .sukiV7,
  ]

}

nonisolated enum Suki_Pb_Ssp_V1_SubstitutionScope: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// No substitution will be performed.
  case none // = 0

  /// Substitution will only be performed for transcripts in Ambient mode.
  case ambient // = 1

  /// Substitution will only be performed for transcripts in Dictation mode.
  case dictation // = 2

  /// Substitution will be performed for both Ambient and Dictation modes.
  case both // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .none
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .none
    case 1: self = .ambient
    case 2: self = .dictation
    case 3: self = .both
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .none: return 0
    case .ambient: return 1
    case .dictation: return 2
    case .both: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Suki_Pb_Ssp_V1_SubstitutionScope] = [
    .none,
    .ambient,
    .dictation,
    .both,
  ]

}

/// SessionTerminatedSignal notifies active streaming clients that the session was
/// ended by another peer/modality.
nonisolated struct Suki_Pb_Ssp_V1_SessionTerminatedSignal: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var reason: Suki_Pb_Ssp_V1_SessionTerminatedSignal.Reason = .unknown

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum Reason: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unknown // = 0
    case cancelled // = 1
    case ended // = 2
    case UNRECOGNIZED(Int)

    init() {
      self = .unknown
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unknown
      case 1: self = .cancelled
      case 2: self = .ended
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unknown: return 0
      case .cancelled: return 1
      case .ended: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Suki_Pb_Ssp_V1_SessionTerminatedSignal.Reason] = [
      .unknown,
      .cancelled,
      .ended,
    ]

  }

  init() {}
}

/// A custom map that contains any client specific data that SSP can handle.enum
/// Usually this requires a flow that can handle the data specific to certain
/// clients SSP can also provide some free form data placeholders that can be
/// used for enhanced funtionality For ex, { "log_level": "verbose" }
nonisolated struct Suki_Pb_Ssp_V1_CustomData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var data: Dictionary<String,String> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Response of SpeechStart rpc.
/// Contains the all important unique session_id that needs to be embedded in
/// metadata of all subsequent rpcs to the platform Contains the information
/// about the asr being used
nonisolated struct Suki_Pb_Ssp_V1_SpeechStartResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sessionID: String = String()

  var speechStartTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_speechStartTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_speechStartTime = newValue}
  }
  /// Returns true if `speechStartTime` has been explicitly set.
  var hasSpeechStartTime: Bool {self._speechStartTime != nil}
  /// Clears the value of `speechStartTime`. Subsequent reads from it will return its default value.
  mutating func clearSpeechStartTime() {self._speechStartTime = nil}

  var asrInfo: Suki_Pb_Ssp_V1_AsrInformation {
    get {_asrInfo ?? Suki_Pb_Ssp_V1_AsrInformation()}
    set {_asrInfo = newValue}
  }
  /// Returns true if `asrInfo` has been explicitly set.
  var hasAsrInfo: Bool {self._asrInfo != nil}
  /// Clears the value of `asrInfo`. Subsequent reads from it will return its default value.
  mutating func clearAsrInfo() {self._asrInfo = nil}

  /// Canonical note/composition id resolved for ambient external/WebSDK flows.
  /// Empty for flows that do not require note_id/session_group_id mapping.
  var noteID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _speechStartTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _asrInfo: Suki_Pb_Ssp_V1_AsrInformation? = nil
}

/// Speech configuration captures aspects of audio session that are used to
/// communicate with ASRs.enum
nonisolated struct Suki_Pb_Ssp_V1_SpeechConfig: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var topic: String {
    get {_storage._topic}
    set {_uniqueStorage()._topic = newValue}
  }

  /// Can use multiple asr types in a session
  var asrs: [Suki_Pb_Ssp_V1_ASR] {
    get {_storage._asrs}
    set {_uniqueStorage()._asrs = newValue}
  }

  var transcriptionConfig: Suki_Pb_Ssp_V1_TranscriptionConfig {
    get {_storage._transcriptionConfig ?? Suki_Pb_Ssp_V1_TranscriptionConfig()}
    set {_uniqueStorage()._transcriptionConfig = newValue}
  }
  /// Returns true if `transcriptionConfig` has been explicitly set.
  var hasTranscriptionConfig: Bool {_storage._transcriptionConfig != nil}
  /// Clears the value of `transcriptionConfig`. Subsequent reads from it will return its default value.
  mutating func clearTranscriptionConfig() {_uniqueStorage()._transcriptionConfig = nil}

  var audioConfiguration: Suki_Pb_Ssp_V1_AudioConfig {
    get {_storage._audioConfiguration ?? Suki_Pb_Ssp_V1_AudioConfig()}
    set {_uniqueStorage()._audioConfiguration = newValue}
  }
  /// Returns true if `audioConfiguration` has been explicitly set.
  var hasAudioConfiguration: Bool {_storage._audioConfiguration != nil}
  /// Clears the value of `audioConfiguration`. Subsequent reads from it will return its default value.
  mutating func clearAudioConfiguration() {_uniqueStorage()._audioConfiguration = nil}

  var modelConfig: Suki_Pb_Ssp_V1_ModelConfig {
    get {_storage._modelConfig ?? Suki_Pb_Ssp_V1_ModelConfig()}
    set {_uniqueStorage()._modelConfig = newValue}
  }
  /// Returns true if `modelConfig` has been explicitly set.
  var hasModelConfig: Bool {_storage._modelConfig != nil}
  /// Clears the value of `modelConfig`. Subsequent reads from it will return its default value.
  mutating func clearModelConfig() {_uniqueStorage()._modelConfig = nil}

  var speechAdaptation: Suki_Pb_Ssp_V1_SpeechAdaptation {
    get {_storage._speechAdaptation ?? Suki_Pb_Ssp_V1_SpeechAdaptation()}
    set {_uniqueStorage()._speechAdaptation = newValue}
  }
  /// Returns true if `speechAdaptation` has been explicitly set.
  var hasSpeechAdaptation: Bool {_storage._speechAdaptation != nil}
  /// Clears the value of `speechAdaptation`. Subsequent reads from it will return its default value.
  mutating func clearSpeechAdaptation() {_uniqueStorage()._speechAdaptation = nil}

  var diarizationConfig: Suki_Pb_Ssp_V1_SpeakerDiarizationConfig {
    get {_storage._diarizationConfig ?? Suki_Pb_Ssp_V1_SpeakerDiarizationConfig()}
    set {_uniqueStorage()._diarizationConfig = newValue}
  }
  /// Returns true if `diarizationConfig` has been explicitly set.
  var hasDiarizationConfig: Bool {_storage._diarizationConfig != nil}
  /// Clears the value of `diarizationConfig`. Subsequent reads from it will return its default value.
  mutating func clearDiarizationConfig() {_uniqueStorage()._diarizationConfig = nil}

  var clientType: Suki_Pb_Ssp_V1_SpeechConfig.ClientType {
    get {_storage._clientType}
    set {_uniqueStorage()._clientType = newValue}
  }

  /// Per-user vocabulary populated by ms-orchestrator once per dictation session
  var userSubstitutions: Dictionary<String,String> {
    get {_storage._userSubstitutions}
    set {_uniqueStorage()._userSubstitutions = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum ClientType: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int

    /// Default value, should not be used by external clients.
    case unspecified // = 0

    /// Embedded clients need to set this field to embedded.
    case embedded // = 1

    /// API clients need to set this field to API.
    case api // = 2
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .embedded
      case 2: self = .api
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .embedded: return 1
      case .api: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Suki_Pb_Ssp_V1_SpeechConfig.ClientType] = [
      .unspecified,
      .embedded,
      .api,
    ]

  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Speaker Diarization Config
nonisolated struct Suki_Pb_Ssp_V1_SpeakerDiarizationConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var enableSpeakerDiarization: Bool = false

  var minNumSpeakers: UInt32 = 0

  var maxNumSpeakers: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Audio related configuration
nonisolated struct Suki_Pb_Ssp_V1_AudioConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var audioEncoding: Suki_Pb_Ssp_V1_AudioEncoding = .unspecifiedEncoding

  var sampleRateHertz: Int32 = 0

  var enableCompression: Bool = false

  /// The [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) language tag
  /// Currently supporting only en-US
  var audioLanguage: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Transcription related configuration that will be considered while sending
/// transcripts to clients.
nonisolated struct Suki_Pb_Ssp_V1_TranscriptionConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var detectEndOfUtterance: Bool = false

  var provideIntermediateResults: Bool = false

  var provideAlternateResults: Bool = false

  /// Ignored if provide_alternate_results is false or not set
  var maxAlternates: Int32 = 0

  var identifyPhi: Bool = false

  /// If true, word time offsets will be returned if the specified ASR<->model
  /// combination supports it.
  var enableWordTimeOffsets: Bool = false

  var substitutionLanguage: Suki_Pb_Ssp_V1_TranscriptionConfig.SubstitutionLanguage = .none

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum SubstitutionLanguage: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int

    /// No substitution will be performed.
    case none // = 0

    /// Substitution will only be performed for English language transcripts.
    case english // = 1
    case UNRECOGNIZED(Int)

    init() {
      self = .none
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .none
      case 1: self = .english
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .none: return 0
      case .english: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Suki_Pb_Ssp_V1_TranscriptionConfig.SubstitutionLanguage] = [
      .none,
      .english,
    ]

  }

  init() {}
}

/// Advanced: Model configuration is for the use cases where the clients needs a
/// specific model to process or perform SSP functionality. Usually, these need
/// not be set and the platform doesn't guarantee that this configuration will be
/// honoured by the ASR / NLP models in cases where it's not applicable i.e. that
/// tenant_id does indeed have the need to use different models.
nonisolated struct Suki_Pb_Ssp_V1_ModelConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Based on specialty or customer id
  var modelName: String = String()

  /// should default to latest stable
  var modelVersion: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Set of configuration that allow SSP to better tune the speech transcription
/// process.
nonisolated struct Suki_Pb_Ssp_V1_SpeechAdaptation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var phraseBiasingSet: [Suki_Pb_Ssp_V1_PhraseBias] = []

  var phraseToleranceSet: [Suki_Pb_Ssp_V1_PhraseTolerance] = []

  /// custom classes
  var languageClassPhrases: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// For simillar sounding words PhraseBias can be used to tune the platform to
/// one word over another or one phrase over another.
nonisolated struct Suki_Pb_Ssp_V1_PhraseBias: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var phraseName: String = String()

  /// [1...10]
  var biasValue: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// For complex or uncommon words where transcription has a tendency to land on
/// unexpected words, use tolerance to
///  suggest that a margin can be used to still conclude the word as expected.
///  Best used in combination with PhraseBias.
nonisolated struct Suki_Pb_Ssp_V1_PhraseTolerance: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var phraseName: String = String()

  var toleranceThreshold: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Audio
nonisolated struct Suki_Pb_Ssp_V1_SpeechContent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var audioData: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Common result for any speech API.
nonisolated struct Suki_Pb_Ssp_V1_SpeechResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var transcriptOrIntent: String = String()

  var confidence: Float = 0

  var words: [Suki_Pb_Ssp_V1_WordMetadata] = []

  var threshold: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Suki_Pb_Ssp_V1_WordMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var word: String = String()

  var startTime: SwiftProtobuf.Google_Protobuf_Duration {
    get {_startTime ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_startTime = newValue}
  }
  /// Returns true if `startTime` has been explicitly set.
  var hasStartTime: Bool {self._startTime != nil}
  /// Clears the value of `startTime`. Subsequent reads from it will return its default value.
  mutating func clearStartTime() {self._startTime = nil}

  var endTime: SwiftProtobuf.Google_Protobuf_Duration {
    get {_endTime ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_endTime = newValue}
  }
  /// Returns true if `endTime` has been explicitly set.
  var hasEndTime: Bool {self._endTime != nil}
  /// Clears the value of `endTime`. Subsequent reads from it will return its default value.
  mutating func clearEndTime() {self._endTime = nil}

  var speaker: Suki_Pb_Ssp_V1_SpeakerInfo {
    get {_speaker ?? Suki_Pb_Ssp_V1_SpeakerInfo()}
    set {_speaker = newValue}
  }
  /// Returns true if `speaker` has been explicitly set.
  var hasSpeaker: Bool {self._speaker != nil}
  /// Clears the value of `speaker`. Subsequent reads from it will return its default value.
  mutating func clearSpeaker() {self._speaker = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _startTime: SwiftProtobuf.Google_Protobuf_Duration? = nil
  fileprivate var _endTime: SwiftProtobuf.Google_Protobuf_Duration? = nil
  fileprivate var _speaker: Suki_Pb_Ssp_V1_SpeakerInfo? = nil
}

nonisolated struct Suki_Pb_Ssp_V1_SpeakerInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Command result.
nonisolated struct Suki_Pb_Ssp_V1_CommandResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var intent: Suki_Pb_Ssp_V1_SpeechResult {
    get {_intent ?? Suki_Pb_Ssp_V1_SpeechResult()}
    set {_intent = newValue}
  }
  /// Returns true if `intent` has been explicitly set.
  var hasIntent: Bool {self._intent != nil}
  /// Clears the value of `intent`. Subsequent reads from it will return its default value.
  mutating func clearIntent() {self._intent = nil}

  var slots: [Suki_Pb_Ssp_V1_Slot] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _intent: Suki_Pb_Ssp_V1_SpeechResult? = nil
}

/// Transcription result.
nonisolated struct Suki_Pb_Ssp_V1_TranscriptResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var transcript: Suki_Pb_Ssp_V1_SpeechResult {
    get {_transcript ?? Suki_Pb_Ssp_V1_SpeechResult()}
    set {_transcript = newValue}
  }
  /// Returns true if `transcript` has been explicitly set.
  var hasTranscript: Bool {self._transcript != nil}
  /// Clears the value of `transcript`. Subsequent reads from it will return its default value.
  mutating func clearTranscript() {self._transcript = nil}

  var isFinal: Bool = false

  var transcriptAlternates: [Suki_Pb_Ssp_V1_SpeechResult] = []

  var asrUsed: Suki_Pb_Ssp_V1_ASR = .default

  /// Final from ASR can have empty transcript,
  /// but app using this proto may have to take some decision on the time of the
  /// audio for this transcript was returned. an example would be BAC-1613.
  var resultEndTime: SwiftProtobuf.Google_Protobuf_Duration {
    get {_resultEndTime ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_resultEndTime = newValue}
  }
  /// Returns true if `resultEndTime` has been explicitly set.
  var hasResultEndTime: Bool {self._resultEndTime != nil}
  /// Clears the value of `resultEndTime`. Subsequent reads from it will return its default value.
  mutating func clearResultEndTime() {self._resultEndTime = nil}

  var modelConfig: Suki_Pb_Ssp_V1_ModelConfig {
    get {_modelConfig ?? Suki_Pb_Ssp_V1_ModelConfig()}
    set {_modelConfig = newValue}
  }
  /// Returns true if `modelConfig` has been explicitly set.
  var hasModelConfig: Bool {self._modelConfig != nil}
  /// Clears the value of `modelConfig`. Subsequent reads from it will return its default value.
  mutating func clearModelConfig() {self._modelConfig = nil}

  /// to uniquely define a transcript, between all the transcripts generated for
  /// a specific session/connection can be used to refer and log (and mask) the
  /// transcript at different services
  var id: String = String()

  /// speech start time when the speech started for the transcript
  var speechStartTime: SwiftProtobuf.Google_Protobuf_Duration {
    get {_speechStartTime ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_speechStartTime = newValue}
  }
  /// Returns true if `speechStartTime` has been explicitly set.
  var hasSpeechStartTime: Bool {self._speechStartTime != nil}
  /// Clears the value of `speechStartTime`. Subsequent reads from it will return its default value.
  mutating func clearSpeechStartTime() {self._speechStartTime = nil}

  ///language detected
  var langID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _transcript: Suki_Pb_Ssp_V1_SpeechResult? = nil
  fileprivate var _resultEndTime: SwiftProtobuf.Google_Protobuf_Duration? = nil
  fileprivate var _modelConfig: Suki_Pb_Ssp_V1_ModelConfig? = nil
  fileprivate var _speechStartTime: SwiftProtobuf.Google_Protobuf_Duration? = nil
}

/// Intent result is the root result of command rpc.
nonisolated struct Suki_Pb_Ssp_V1_IntentResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var intent: Suki_Pb_Ssp_V1_CommandResult {
    get {_intent ?? Suki_Pb_Ssp_V1_CommandResult()}
    set {_intent = newValue}
  }
  /// Returns true if `intent` has been explicitly set.
  var hasIntent: Bool {self._intent != nil}
  /// Clears the value of `intent`. Subsequent reads from it will return its default value.
  mutating func clearIntent() {self._intent = nil}

  var intentType: String = String()

  var intentAlternates: [Suki_Pb_Ssp_V1_CommandResult] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _intent: Suki_Pb_Ssp_V1_CommandResult? = nil
}

/// Slot related parameters.
nonisolated struct Suki_Pb_Ssp_V1_Slot: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var slotName: String = String()

  var slotType: String = String()

  var confidence: Float = 0

  var threshold: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Asr Information
nonisolated struct Suki_Pb_Ssp_V1_AsrInformation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Type of Asr used for transcription
  var asrType: Suki_Pb_Ssp_V1_ASR = .default

  /// Model configuration of the asr being used
  var modelConfig: Suki_Pb_Ssp_V1_ModelConfig {
    get {_modelConfig ?? Suki_Pb_Ssp_V1_ModelConfig()}
    set {_modelConfig = newValue}
  }
  /// Returns true if `modelConfig` has been explicitly set.
  var hasModelConfig: Bool {self._modelConfig != nil}
  /// Clears the value of `modelConfig`. Subsequent reads from it will return its default value.
  mutating func clearModelConfig() {self._modelConfig = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _modelConfig: Suki_Pb_Ssp_V1_ModelConfig? = nil
}

nonisolated struct Suki_Pb_Ssp_V1_QnAContext: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var patient: Suki_Pb_Ssp_V1_Patient {
    get {_patient ?? Suki_Pb_Ssp_V1_Patient()}
    set {_patient = newValue}
  }
  /// Returns true if `patient` has been explicitly set.
  var hasPatient: Bool {self._patient != nil}
  /// Clears the value of `patient`. Subsequent reads from it will return its default value.
  mutating func clearPatient() {self._patient = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _patient: Suki_Pb_Ssp_V1_Patient? = nil
}

nonisolated struct Suki_Pb_Ssp_V1_QnAAnswer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var query: String = String()

  /// ULID to indicate generation
  var generationID: String = String()

  var status: Suki_Pb_Ssp_V1_AnswerStatus = .unknownStatus

  var knowledgeSources: [Suki_Pb_Qna_KnowledgeSource] = []

  var answerContents: [SwiftProtobuf.Google_Protobuf_Struct] = []

  /// Deprecated: As Each Answer Content now has its own timestamp
  ///
  /// NOTE: This field was marked as deprecated in the .proto file.
  var lastFhirUpdatedTimestamp: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_lastFhirUpdatedTimestamp ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_lastFhirUpdatedTimestamp = newValue}
  }
  /// Returns true if `lastFhirUpdatedTimestamp` has been explicitly set.
  var hasLastFhirUpdatedTimestamp: Bool {self._lastFhirUpdatedTimestamp != nil}
  /// Clears the value of `lastFhirUpdatedTimestamp`. Subsequent reads from it will return its default value.
  mutating func clearLastFhirUpdatedTimestamp() {self._lastFhirUpdatedTimestamp = nil}

  var gmkAnswer: Suki_Pb_Qna_GMKAnswerComponent {
    get {_gmkAnswer ?? Suki_Pb_Qna_GMKAnswerComponent()}
    set {_gmkAnswer = newValue}
  }
  /// Returns true if `gmkAnswer` has been explicitly set.
  var hasGmkAnswer: Bool {self._gmkAnswer != nil}
  /// Clears the value of `gmkAnswer`. Subsequent reads from it will return its default value.
  mutating func clearGmkAnswer() {self._gmkAnswer = nil}

  /// Forwarded from qna_pb2.QnAResponse.knowledge_source_versions.
  /// Populated by ms-orchestrator's CreateSspQnAResponseFromMLResponse() mapping.
  var knowledgeSourceVersions: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _lastFhirUpdatedTimestamp: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _gmkAnswer: Suki_Pb_Qna_GMKAnswerComponent? = nil
}

nonisolated struct Suki_Pb_Ssp_V1_Patient: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sukiPatientID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "suki.pb.ssp.v1"

nonisolated extension Suki_Pb_Ssp_V1_RequestSignals: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNSPECIFIED_REQUEST_SIGNAL\0\u{1}SPEECH_PAUSE\0\u{1}SPEECH_RESUME\0\u{1}SPEECH_ABORT\0\u{1}COMMAND_CUE\0\u{2}.SPEECH_END\0")
}

nonisolated extension Suki_Pb_Ssp_V1_ResponseSignals: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNSPECIFIED_RESPONSE_SIGNAL\0\u{1}END_OF_UTTERANCE\0\u{1}KEEP_ALIVE\0\u{1}SPEECH_PROCESSED\0\u{1}SPEECH_CONFIG_CHANGED\0\u{1}SPEECH_PAUSED\0\u{1}SPEECH_RESUMED\0\u{1}SPEECH_ABORTED\0")
}

nonisolated extension Suki_Pb_Ssp_V1_ErrorSignals: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNSPECIFIED_ERROR_SIGNAL\0\u{1}SPEECH_CONFIG_ERROR\0\u{1}UNSUPPORTED_REQUEST\0\u{1}INSUFFICIENT_PERMISSIONS\0\u{1}INVALID_TOKEN\0\u{1}AUTHENTICATION_ERROR\0\u{2}-GENERAL_ERROR\0")
}

nonisolated extension Suki_Pb_Ssp_V1_AudioEncoding: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNSPECIFIED_ENCODING\0\u{9}LINEAR16\0\u{1}PCM_16KHZ\0\u{1}OGG_OPUS\0")
}

nonisolated extension Suki_Pb_Ssp_V1_ServiceType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNKNOWN_SERVICE\0\u{1}TRANSCRIPTION\0\u{1}AMBIENT\0\u{1}QNA\0\u{1}IUSF\0\u{1}FORM_FILLING\0\u{1}CODE_GENERATION\0")
}

nonisolated extension Suki_Pb_Ssp_V1_AnswerStatus: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNKNOWN_STATUS\0\u{1}ANSWER_FOUND\0\u{1}NO_ANSWER_FOUND\0\u{1}QUERY_NOT_SUPPORTED\0\u{1}ERROR_OCCURRED\0")
}

nonisolated extension Suki_Pb_Ssp_V1_LANGUAGE: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0Default\0\u{1}English\0\u{1}Multilingual\0")
}

nonisolated extension Suki_Pb_Ssp_V1_ASR: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DEFAULT\0\u{1}SUKI\0\u{1}GOOGLE\0\u{2}\u{2}SUKI_V2\0\u{1}NVOQ\0\u{1}SUKI_V4\0\u{1}SUKI_V5\0\u{1}SUKI_V6\0\u{1}SUKI_V7\0")
}

nonisolated extension Suki_Pb_Ssp_V1_SubstitutionScope: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0None\0\u{1}Ambient\0\u{1}Dictation\0\u{1}Both\0")
}

nonisolated extension Suki_Pb_Ssp_V1_SessionTerminatedSignal: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SessionTerminatedSignal"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reason\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.reason) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.reason != .unknown {
      try visitor.visitSingularEnumField(value: self.reason, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_SessionTerminatedSignal, rhs: Suki_Pb_Ssp_V1_SessionTerminatedSignal) -> Bool {
    if lhs.reason != rhs.reason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_SessionTerminatedSignal.Reason: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0REASON_UNKNOWN\0\u{1}CANCELLED\0\u{1}ENDED\0")
}

nonisolated extension Suki_Pb_Ssp_V1_CustomData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CustomData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}data\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.data) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.data.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.data, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_CustomData, rhs: Suki_Pb_Ssp_V1_CustomData) -> Bool {
    if lhs.data != rhs.data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_SpeechStartResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SpeechStartResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0\u{3}speech_start_time\0\u{3}asr_info\0\u{3}note_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sessionID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._speechStartTime) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._asrInfo) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.noteID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.sessionID.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionID, fieldNumber: 1)
    }
    try { if let v = self._speechStartTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._asrInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.noteID.isEmpty {
      try visitor.visitSingularStringField(value: self.noteID, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_SpeechStartResult, rhs: Suki_Pb_Ssp_V1_SpeechStartResult) -> Bool {
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs._speechStartTime != rhs._speechStartTime {return false}
    if lhs._asrInfo != rhs._asrInfo {return false}
    if lhs.noteID != rhs.noteID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_SpeechConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SpeechConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}topic\0\u{1}asrs\0\u{3}transcription_config\0\u{3}audio_configuration\0\u{3}model_config\0\u{3}speech_adaptation\0\u{3}diarization_config\0\u{3}client_type\0\u{3}user_substitutions\0")

  fileprivate class _StorageClass {
    var _topic: String = String()
    var _asrs: [Suki_Pb_Ssp_V1_ASR] = []
    var _transcriptionConfig: Suki_Pb_Ssp_V1_TranscriptionConfig? = nil
    var _audioConfiguration: Suki_Pb_Ssp_V1_AudioConfig? = nil
    var _modelConfig: Suki_Pb_Ssp_V1_ModelConfig? = nil
    var _speechAdaptation: Suki_Pb_Ssp_V1_SpeechAdaptation? = nil
    var _diarizationConfig: Suki_Pb_Ssp_V1_SpeakerDiarizationConfig? = nil
    var _clientType: Suki_Pb_Ssp_V1_SpeechConfig.ClientType = .unspecified
    var _userSubstitutions: Dictionary<String,String> = [:]

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _topic = source._topic
      _asrs = source._asrs
      _transcriptionConfig = source._transcriptionConfig
      _audioConfiguration = source._audioConfiguration
      _modelConfig = source._modelConfig
      _speechAdaptation = source._speechAdaptation
      _diarizationConfig = source._diarizationConfig
      _clientType = source._clientType
      _userSubstitutions = source._userSubstitutions
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._topic) }()
        case 2: try { try decoder.decodeRepeatedEnumField(value: &_storage._asrs) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._transcriptionConfig) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._audioConfiguration) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._modelConfig) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._speechAdaptation) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._diarizationConfig) }()
        case 8: try { try decoder.decodeSingularEnumField(value: &_storage._clientType) }()
        case 9: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._userSubstitutions) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._topic.isEmpty {
        try visitor.visitSingularStringField(value: _storage._topic, fieldNumber: 1)
      }
      if !_storage._asrs.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._asrs, fieldNumber: 2)
      }
      try { if let v = _storage._transcriptionConfig {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._audioConfiguration {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._modelConfig {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._speechAdaptation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._diarizationConfig {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      if _storage._clientType != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._clientType, fieldNumber: 8)
      }
      if !_storage._userSubstitutions.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._userSubstitutions, fieldNumber: 9)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_SpeechConfig, rhs: Suki_Pb_Ssp_V1_SpeechConfig) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._topic != rhs_storage._topic {return false}
        if _storage._asrs != rhs_storage._asrs {return false}
        if _storage._transcriptionConfig != rhs_storage._transcriptionConfig {return false}
        if _storage._audioConfiguration != rhs_storage._audioConfiguration {return false}
        if _storage._modelConfig != rhs_storage._modelConfig {return false}
        if _storage._speechAdaptation != rhs_storage._speechAdaptation {return false}
        if _storage._diarizationConfig != rhs_storage._diarizationConfig {return false}
        if _storage._clientType != rhs_storage._clientType {return false}
        if _storage._userSubstitutions != rhs_storage._userSubstitutions {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_SpeechConfig.ClientType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNSPECIFIED\0\u{1}EMBEDDED\0\u{1}API\0")
}

nonisolated extension Suki_Pb_Ssp_V1_SpeakerDiarizationConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SpeakerDiarizationConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}enable_speaker_diarization\0\u{3}min_num_speakers\0\u{3}max_num_speakers\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enableSpeakerDiarization) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.minNumSpeakers) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.maxNumSpeakers) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enableSpeakerDiarization != false {
      try visitor.visitSingularBoolField(value: self.enableSpeakerDiarization, fieldNumber: 1)
    }
    if self.minNumSpeakers != 0 {
      try visitor.visitSingularUInt32Field(value: self.minNumSpeakers, fieldNumber: 2)
    }
    if self.maxNumSpeakers != 0 {
      try visitor.visitSingularUInt32Field(value: self.maxNumSpeakers, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_SpeakerDiarizationConfig, rhs: Suki_Pb_Ssp_V1_SpeakerDiarizationConfig) -> Bool {
    if lhs.enableSpeakerDiarization != rhs.enableSpeakerDiarization {return false}
    if lhs.minNumSpeakers != rhs.minNumSpeakers {return false}
    if lhs.maxNumSpeakers != rhs.maxNumSpeakers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_AudioConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AudioConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}audio_encoding\0\u{3}sample_rate_hertz\0\u{3}enable_compression\0\u{3}audio_language\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.audioEncoding) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.sampleRateHertz) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.enableCompression) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.audioLanguage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.audioEncoding != .unspecifiedEncoding {
      try visitor.visitSingularEnumField(value: self.audioEncoding, fieldNumber: 1)
    }
    if self.sampleRateHertz != 0 {
      try visitor.visitSingularInt32Field(value: self.sampleRateHertz, fieldNumber: 2)
    }
    if self.enableCompression != false {
      try visitor.visitSingularBoolField(value: self.enableCompression, fieldNumber: 3)
    }
    if !self.audioLanguage.isEmpty {
      try visitor.visitSingularStringField(value: self.audioLanguage, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_AudioConfig, rhs: Suki_Pb_Ssp_V1_AudioConfig) -> Bool {
    if lhs.audioEncoding != rhs.audioEncoding {return false}
    if lhs.sampleRateHertz != rhs.sampleRateHertz {return false}
    if lhs.enableCompression != rhs.enableCompression {return false}
    if lhs.audioLanguage != rhs.audioLanguage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_TranscriptionConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TranscriptionConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}detect_end_of_utterance\0\u{3}provide_intermediate_results\0\u{3}provide_alternate_results\0\u{3}max_alternates\0\u{3}identify_phi\0\u{3}enable_word_time_offsets\0\u{3}substitution_language\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.detectEndOfUtterance) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.provideIntermediateResults) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.provideAlternateResults) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.maxAlternates) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.identifyPhi) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.enableWordTimeOffsets) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self.substitutionLanguage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.detectEndOfUtterance != false {
      try visitor.visitSingularBoolField(value: self.detectEndOfUtterance, fieldNumber: 1)
    }
    if self.provideIntermediateResults != false {
      try visitor.visitSingularBoolField(value: self.provideIntermediateResults, fieldNumber: 2)
    }
    if self.provideAlternateResults != false {
      try visitor.visitSingularBoolField(value: self.provideAlternateResults, fieldNumber: 3)
    }
    if self.maxAlternates != 0 {
      try visitor.visitSingularInt32Field(value: self.maxAlternates, fieldNumber: 4)
    }
    if self.identifyPhi != false {
      try visitor.visitSingularBoolField(value: self.identifyPhi, fieldNumber: 5)
    }
    if self.enableWordTimeOffsets != false {
      try visitor.visitSingularBoolField(value: self.enableWordTimeOffsets, fieldNumber: 6)
    }
    if self.substitutionLanguage != .none {
      try visitor.visitSingularEnumField(value: self.substitutionLanguage, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_TranscriptionConfig, rhs: Suki_Pb_Ssp_V1_TranscriptionConfig) -> Bool {
    if lhs.detectEndOfUtterance != rhs.detectEndOfUtterance {return false}
    if lhs.provideIntermediateResults != rhs.provideIntermediateResults {return false}
    if lhs.provideAlternateResults != rhs.provideAlternateResults {return false}
    if lhs.maxAlternates != rhs.maxAlternates {return false}
    if lhs.identifyPhi != rhs.identifyPhi {return false}
    if lhs.enableWordTimeOffsets != rhs.enableWordTimeOffsets {return false}
    if lhs.substitutionLanguage != rhs.substitutionLanguage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_TranscriptionConfig.SubstitutionLanguage: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NONE\0\u{1}ENGLISH\0")
}

nonisolated extension Suki_Pb_Ssp_V1_ModelConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ModelConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}model_name\0\u{3}model_version\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.modelName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.modelVersion) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.modelName.isEmpty {
      try visitor.visitSingularStringField(value: self.modelName, fieldNumber: 1)
    }
    if !self.modelVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.modelVersion, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_ModelConfig, rhs: Suki_Pb_Ssp_V1_ModelConfig) -> Bool {
    if lhs.modelName != rhs.modelName {return false}
    if lhs.modelVersion != rhs.modelVersion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_SpeechAdaptation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SpeechAdaptation"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}phrase_biasing_set\0\u{3}phrase_tolerance_set\0\u{3}language_class_phrases\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.phraseBiasingSet) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.phraseToleranceSet) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.languageClassPhrases) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.phraseBiasingSet.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.phraseBiasingSet, fieldNumber: 1)
    }
    if !self.phraseToleranceSet.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.phraseToleranceSet, fieldNumber: 2)
    }
    if !self.languageClassPhrases.isEmpty {
      try visitor.visitRepeatedStringField(value: self.languageClassPhrases, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_SpeechAdaptation, rhs: Suki_Pb_Ssp_V1_SpeechAdaptation) -> Bool {
    if lhs.phraseBiasingSet != rhs.phraseBiasingSet {return false}
    if lhs.phraseToleranceSet != rhs.phraseToleranceSet {return false}
    if lhs.languageClassPhrases != rhs.languageClassPhrases {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_PhraseBias: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PhraseBias"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}phrase_name\0\u{3}bias_value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.phraseName) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.biasValue) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.phraseName.isEmpty {
      try visitor.visitSingularStringField(value: self.phraseName, fieldNumber: 1)
    }
    if self.biasValue != 0 {
      try visitor.visitSingularInt32Field(value: self.biasValue, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_PhraseBias, rhs: Suki_Pb_Ssp_V1_PhraseBias) -> Bool {
    if lhs.phraseName != rhs.phraseName {return false}
    if lhs.biasValue != rhs.biasValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_PhraseTolerance: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PhraseTolerance"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}phrase_name\0\u{3}tolerance_threshold\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.phraseName) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.toleranceThreshold) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.phraseName.isEmpty {
      try visitor.visitSingularStringField(value: self.phraseName, fieldNumber: 1)
    }
    if self.toleranceThreshold.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.toleranceThreshold, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_PhraseTolerance, rhs: Suki_Pb_Ssp_V1_PhraseTolerance) -> Bool {
    if lhs.phraseName != rhs.phraseName {return false}
    if lhs.toleranceThreshold != rhs.toleranceThreshold {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_SpeechContent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SpeechContent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}audio_data\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.audioData) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.audioData.isEmpty {
      try visitor.visitSingularBytesField(value: self.audioData, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_SpeechContent, rhs: Suki_Pb_Ssp_V1_SpeechContent) -> Bool {
    if lhs.audioData != rhs.audioData {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_SpeechResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SpeechResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}transcript_or_intent\0\u{1}confidence\0\u{1}words\0\u{1}threshold\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.transcriptOrIntent) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.confidence) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.words) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.threshold) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.transcriptOrIntent.isEmpty {
      try visitor.visitSingularStringField(value: self.transcriptOrIntent, fieldNumber: 1)
    }
    if self.confidence.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.confidence, fieldNumber: 2)
    }
    if !self.words.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.words, fieldNumber: 3)
    }
    if self.threshold.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.threshold, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_SpeechResult, rhs: Suki_Pb_Ssp_V1_SpeechResult) -> Bool {
    if lhs.transcriptOrIntent != rhs.transcriptOrIntent {return false}
    if lhs.confidence != rhs.confidence {return false}
    if lhs.words != rhs.words {return false}
    if lhs.threshold != rhs.threshold {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_WordMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WordMetadata"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}word\0\u{3}start_time\0\u{3}end_time\0\u{1}speaker\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.word) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._startTime) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._endTime) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._speaker) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.word.isEmpty {
      try visitor.visitSingularStringField(value: self.word, fieldNumber: 1)
    }
    try { if let v = self._startTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._endTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._speaker {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_WordMetadata, rhs: Suki_Pb_Ssp_V1_WordMetadata) -> Bool {
    if lhs.word != rhs.word {return false}
    if lhs._startTime != rhs._startTime {return false}
    if lhs._endTime != rhs._endTime {return false}
    if lhs._speaker != rhs._speaker {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_SpeakerInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SpeakerInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_SpeakerInfo, rhs: Suki_Pb_Ssp_V1_SpeakerInfo) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_CommandResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CommandResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}intent\0\u{1}slots\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._intent) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.slots) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._intent {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.slots.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.slots, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_CommandResult, rhs: Suki_Pb_Ssp_V1_CommandResult) -> Bool {
    if lhs._intent != rhs._intent {return false}
    if lhs.slots != rhs.slots {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_TranscriptResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TranscriptResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}transcript\0\u{3}is_final\0\u{3}transcript_alternates\0\u{3}asr_used\0\u{3}result_end_time\0\u{3}model_config\0\u{1}id\0\u{3}speech_start_time\0\u{3}lang_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._transcript) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isFinal) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.transcriptAlternates) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.asrUsed) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._resultEndTime) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._modelConfig) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._speechStartTime) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.langID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._transcript {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.isFinal != false {
      try visitor.visitSingularBoolField(value: self.isFinal, fieldNumber: 2)
    }
    if !self.transcriptAlternates.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.transcriptAlternates, fieldNumber: 3)
    }
    if self.asrUsed != .default {
      try visitor.visitSingularEnumField(value: self.asrUsed, fieldNumber: 4)
    }
    try { if let v = self._resultEndTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._modelConfig {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 7)
    }
    try { if let v = self._speechStartTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    if !self.langID.isEmpty {
      try visitor.visitSingularStringField(value: self.langID, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_TranscriptResult, rhs: Suki_Pb_Ssp_V1_TranscriptResult) -> Bool {
    if lhs._transcript != rhs._transcript {return false}
    if lhs.isFinal != rhs.isFinal {return false}
    if lhs.transcriptAlternates != rhs.transcriptAlternates {return false}
    if lhs.asrUsed != rhs.asrUsed {return false}
    if lhs._resultEndTime != rhs._resultEndTime {return false}
    if lhs._modelConfig != rhs._modelConfig {return false}
    if lhs.id != rhs.id {return false}
    if lhs._speechStartTime != rhs._speechStartTime {return false}
    if lhs.langID != rhs.langID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_IntentResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".IntentResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}intent\0\u{3}intent_type\0\u{3}intent_alternates\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._intent) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.intentType) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.intentAlternates) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._intent {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.intentType.isEmpty {
      try visitor.visitSingularStringField(value: self.intentType, fieldNumber: 2)
    }
    if !self.intentAlternates.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.intentAlternates, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_IntentResult, rhs: Suki_Pb_Ssp_V1_IntentResult) -> Bool {
    if lhs._intent != rhs._intent {return false}
    if lhs.intentType != rhs.intentType {return false}
    if lhs.intentAlternates != rhs.intentAlternates {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_Slot: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Slot"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}slot_name\0\u{3}slot_type\0\u{1}confidence\0\u{1}threshold\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.slotName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.slotType) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.confidence) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.threshold) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.slotName.isEmpty {
      try visitor.visitSingularStringField(value: self.slotName, fieldNumber: 1)
    }
    if !self.slotType.isEmpty {
      try visitor.visitSingularStringField(value: self.slotType, fieldNumber: 2)
    }
    if self.confidence.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.confidence, fieldNumber: 3)
    }
    if self.threshold.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.threshold, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_Slot, rhs: Suki_Pb_Ssp_V1_Slot) -> Bool {
    if lhs.slotName != rhs.slotName {return false}
    if lhs.slotType != rhs.slotType {return false}
    if lhs.confidence != rhs.confidence {return false}
    if lhs.threshold != rhs.threshold {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_AsrInformation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AsrInformation"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}asr_type\0\u{3}model_config\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.asrType) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._modelConfig) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.asrType != .default {
      try visitor.visitSingularEnumField(value: self.asrType, fieldNumber: 1)
    }
    try { if let v = self._modelConfig {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_AsrInformation, rhs: Suki_Pb_Ssp_V1_AsrInformation) -> Bool {
    if lhs.asrType != rhs.asrType {return false}
    if lhs._modelConfig != rhs._modelConfig {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_QnAContext: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".QnAContext"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}patient\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._patient) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._patient {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_QnAContext, rhs: Suki_Pb_Ssp_V1_QnAContext) -> Bool {
    if lhs._patient != rhs._patient {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_QnAAnswer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".QnAAnswer"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}query\0\u{3}generation_id\0\u{1}status\0\u{3}knowledge_sources\0\u{3}answer_contents\0\u{3}last_fhir_updated_timestamp\0\u{3}gmk_answer\0\u{3}knowledge_source_versions\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.query) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.generationID) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 4: try { try decoder.decodeRepeatedEnumField(value: &self.knowledgeSources) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.answerContents) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._lastFhirUpdatedTimestamp) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._gmkAnswer) }()
      case 8: try { try decoder.decodeRepeatedStringField(value: &self.knowledgeSourceVersions) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.query.isEmpty {
      try visitor.visitSingularStringField(value: self.query, fieldNumber: 1)
    }
    if !self.generationID.isEmpty {
      try visitor.visitSingularStringField(value: self.generationID, fieldNumber: 2)
    }
    if self.status != .unknownStatus {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 3)
    }
    if !self.knowledgeSources.isEmpty {
      try visitor.visitPackedEnumField(value: self.knowledgeSources, fieldNumber: 4)
    }
    if !self.answerContents.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.answerContents, fieldNumber: 5)
    }
    try { if let v = self._lastFhirUpdatedTimestamp {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._gmkAnswer {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    if !self.knowledgeSourceVersions.isEmpty {
      try visitor.visitRepeatedStringField(value: self.knowledgeSourceVersions, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_QnAAnswer, rhs: Suki_Pb_Ssp_V1_QnAAnswer) -> Bool {
    if lhs.query != rhs.query {return false}
    if lhs.generationID != rhs.generationID {return false}
    if lhs.status != rhs.status {return false}
    if lhs.knowledgeSources != rhs.knowledgeSources {return false}
    if lhs.answerContents != rhs.answerContents {return false}
    if lhs._lastFhirUpdatedTimestamp != rhs._lastFhirUpdatedTimestamp {return false}
    if lhs._gmkAnswer != rhs._gmkAnswer {return false}
    if lhs.knowledgeSourceVersions != rhs.knowledgeSourceVersions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Ssp_V1_Patient: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Patient"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}suki_patient_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sukiPatientID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sukiPatientID.isEmpty {
      try visitor.visitSingularStringField(value: self.sukiPatientID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Ssp_V1_Patient, rhs: Suki_Pb_Ssp_V1_Patient) -> Bool {
    if lhs.sukiPatientID != rhs.sukiPatientID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
