// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: learningmotors/pb/macros/macros.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Example Macro: Physical exam macro for normal left knee
/// This would map to having the tags:
/// - name: 'Physical Exam', type: MACRO_TYPE
/// - name: 'Normal Left/Right Knee', type: MACRO_TAG
/// One block:
/// - section_id: 'physical-exam'
/// - content 'Inspection: positive effusion, medial joint line tenderness.'
/// - fields:
///  -- name: 'Inspection', type: BLOCK_TAG
struct Learningmotors_Pb_Macros_Macro {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unique identifier for this macro
  var id: String = String()

  /// ID of user that this macro belongs to
  var userID: String = String()

  /// Collection of tags applicable to this macro
  var tags: [Learningmotors_Pb_Macros_Tag] = []

  /// Collection of blocks that will be applied when this macro is invoked
  var blocks: [Learningmotors_Pb_Macros_Block] = []

  /// Timestamp when this macro was initially created
  var createdAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _createdAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  var hasCreatedAt: Bool {return self._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  mutating func clearCreatedAt() {self._createdAt = nil}

  /// Timestamp when this macro was last updated
  var updatedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _updatedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_updatedAt = newValue}
  }
  /// Returns true if `updatedAt` has been explicitly set.
  var hasUpdatedAt: Bool {return self._updatedAt != nil}
  /// Clears the value of `updatedAt`. Subsequent reads from it will return its default value.
  mutating func clearUpdatedAt() {self._updatedAt = nil}

  /// Timestamp when this macro was flagged as deleted
  var deletedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _deletedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_deletedAt = newValue}
  }
  /// Returns true if `deletedAt` has been explicitly set.
  var hasDeletedAt: Bool {return self._deletedAt != nil}
  /// Clears the value of `deletedAt`. Subsequent reads from it will return its default value.
  mutating func clearDeletedAt() {self._deletedAt = nil}

  /// Specialties field for self service onboarding
  var specialties: [Learningmotors_Pb_User_Specialty] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _createdAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _updatedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _deletedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// A block defines the text that will be applied to a note
struct Learningmotors_Pb_Macros_Block {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The unique section identifier to apply this block to in a note
  var sectionID: String = String()

  /// The content of this block to apply to a note
  var content: String = String()

  /// Collection of tags that have been derived from the 'content' field. Will be ignored on any rpc request but will
  /// be populated in rpc responses when requested.
  var fields: [Learningmotors_Pb_Macros_Tag] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Semantic tag used for the purpose of identifying various slots in a macro.
/// - Used by UI for categorizing and rendering macros.
/// - Used by intent extractor to identify various information in slots.
struct Learningmotors_Pb_Macros_Tag {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name of this tag for display/matching purposes
  /// *required*
  var name: Learningmotors_Pb_Macros_SlotName {
    get {return _name ?? Learningmotors_Pb_Macros_SlotName()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  var hasName: Bool {return self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  mutating func clearName() {self._name = nil}

  /// Type of this tag
  /// *required*
  var type: Learningmotors_Pb_Macros_Tag.TypeEnum = .default

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum TypeEnum: SwiftProtobuf.Enum {
    typealias RawValue = Int

    /// Invalid value to be used as an error marker
    case `default` // = 0

    /// Denotes tag is high-level macro
    case macroType // = 1

    /// Discriminator tag to differentiate between different high-level macro tags
    case macroTag // = 2

    /// Denotes tag within a macro block
    case blockTag // = 3

    /// Denotes tag contains the name of the macro used for voice invocation and the top level name
    case macroName // = 4
    case UNRECOGNIZED(Int)

    init() {
      self = .default
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .default
      case 1: self = .macroType
      case 2: self = .macroTag
      case 3: self = .blockTag
      case 4: self = .macroName
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .default: return 0
      case .macroType: return 1
      case .macroTag: return 2
      case .blockTag: return 3
      case .macroName: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  init() {}

  fileprivate var _name: Learningmotors_Pb_Macros_SlotName? = nil
}

#if swift(>=4.2)

extension Learningmotors_Pb_Macros_Tag.TypeEnum: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Learningmotors_Pb_Macros_Tag.TypeEnum] = [
    .default,
    .macroType,
    .macroTag,
    .blockTag,
    .macroName,
  ]
}

#endif  // swift(>=4.2)

/// Request for rpc CopyMacro
struct Learningmotors_Pb_Macros_CopyMacroRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the macro to copy
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// ID of the source macro to copy from
  /// *required*
  var id: String = String()

  /// ID of the user to copy the macro to
  /// If not specified, the copy returned will belong to the user_id associated with the existing macro
  var userID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

/// Response for rpc CopyMacro
struct Learningmotors_Pb_Macros_CopyMacroResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The newly copied macro. It's ID will be different than the original.
  var macro: Learningmotors_Pb_Macros_Macro {
    get {return _macro ?? Learningmotors_Pb_Macros_Macro()}
    set {_macro = newValue}
  }
  /// Returns true if `macro` has been explicitly set.
  var hasMacro: Bool {return self._macro != nil}
  /// Clears the value of `macro`. Subsequent reads from it will return its default value.
  mutating func clearMacro() {self._macro = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _macro: Learningmotors_Pb_Macros_Macro? = nil
}

/// Request for CopyMacroBySpecialties
struct Learningmotors_Pb_Macros_CopyMacroBySpecialtiesRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Specialties field by which to filter by
  /// *required*
  var specialties: [Learningmotors_Pb_User_Specialty] = []

  /// OrganizationID of org to copy macros to
  /// *required*
  var organizationID: String = String()

  /// UserID of user to copy macros to
  /// *required*
  var userID: String = String()

  /// Map of default_org_section_id:new_org_section_ids used for linking copied macros to sections in the target org
  /// *required*
  var defaultToNewSectionIds: Dictionary<String,String> = [:]

  /// A flag that indicates whether copy was done for particular specialties or for N/A from notetypes
  var specialtiesNaflag: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Response for CopyMacroBySpecialties
struct Learningmotors_Pb_Macros_CopyMacroBySpecialtiesResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The count of notetypes that were copied
  var count: Int32 = 0

  /// Ids of notetypes that were copied
  var ids: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Request for rpc CreateMacro
struct Learningmotors_Pb_Macros_CreateMacroRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// *required*
  var macro: Learningmotors_Pb_Macros_Macro {
    get {return _macro ?? Learningmotors_Pb_Macros_Macro()}
    set {_macro = newValue}
  }
  /// Returns true if `macro` has been explicitly set.
  var hasMacro: Bool {return self._macro != nil}
  /// Clears the value of `macro`. Subsequent reads from it will return its default value.
  mutating func clearMacro() {self._macro = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
  fileprivate var _macro: Learningmotors_Pb_Macros_Macro? = nil
}

/// Response for rpc CreateMacro
struct Learningmotors_Pb_Macros_CreateMacroResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var macro: Learningmotors_Pb_Macros_Macro {
    get {return _macro ?? Learningmotors_Pb_Macros_Macro()}
    set {_macro = newValue}
  }
  /// Returns true if `macro` has been explicitly set.
  var hasMacro: Bool {return self._macro != nil}
  /// Clears the value of `macro`. Subsequent reads from it will return its default value.
  mutating func clearMacro() {self._macro = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _macro: Learningmotors_Pb_Macros_Macro? = nil
}

/// Request for rpc GetMacros
/// The various fields serve as filter criteria. The more fields passed in the request, the more constrained the
/// response will be.
/// See below for results when filtering by name
struct Learningmotors_Pb_Macros_GetMacrosRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// If present, filter by macro ids
  var ids: [String] = []

  /// If present, filter by user id
  var userID: String = String()

  /// If present, the fields of a Block will be derived and populated in GetMacrosResponse
  var includeFields: Bool = false

  /// If present, filter by any macro names which contain this substring. The results will be
  /// deduped by macro name with a case insensitive match. If there is more than one macro with the same name in the
  /// results, the macro with the most aliases for the macro name will be returned. The results will be returned in
  /// alphabetical order by macro name
  var name: String = String()

  /// If present, get the number of results.
  /// Only supports LIMIT field.
  var pageRequest: Learningmotors_Pb_PageRequest {
    get {return _pageRequest ?? Learningmotors_Pb_PageRequest()}
    set {_pageRequest = newValue}
  }
  /// Returns true if `pageRequest` has been explicitly set.
  var hasPageRequest: Bool {return self._pageRequest != nil}
  /// Clears the value of `pageRequest`. Subsequent reads from it will return its default value.
  mutating func clearPageRequest() {self._pageRequest = nil}

  /// If present, filter by specialties.
  var specialties: [Learningmotors_Pb_User_Specialty] = []

  /// A flag to determine whether the request is empty or not
  var specialtiesEmpty: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
  fileprivate var _pageRequest: Learningmotors_Pb_PageRequest? = nil
}

/// Response for rpc GetMacros
struct Learningmotors_Pb_Macros_GetMacrosResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var macros: [Learningmotors_Pb_Macros_Macro] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Request for rpc UpdateMacro
struct Learningmotors_Pb_Macros_UpdateMacroRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// *required*
  var macro: Learningmotors_Pb_Macros_Macro {
    get {return _macro ?? Learningmotors_Pb_Macros_Macro()}
    set {_macro = newValue}
  }
  /// Returns true if `macro` has been explicitly set.
  var hasMacro: Bool {return self._macro != nil}
  /// Clears the value of `macro`. Subsequent reads from it will return its default value.
  mutating func clearMacro() {self._macro = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
  fileprivate var _macro: Learningmotors_Pb_Macros_Macro? = nil
}

/// Response for rpc UpdateMacro
struct Learningmotors_Pb_Macros_UpdateMacroResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var macro: Learningmotors_Pb_Macros_Macro {
    get {return _macro ?? Learningmotors_Pb_Macros_Macro()}
    set {_macro = newValue}
  }
  /// Returns true if `macro` has been explicitly set.
  var hasMacro: Bool {return self._macro != nil}
  /// Clears the value of `macro`. Subsequent reads from it will return its default value.
  mutating func clearMacro() {self._macro = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _macro: Learningmotors_Pb_Macros_Macro? = nil
}

/// Request for rpc DeleteMacros
struct Learningmotors_Pb_Macros_DeleteMacrosRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// IDs of the macros to delete
  /// *required*
  var ids: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

/// Slot definition. This is used as part of specifying the structure of a slot and input for intent
/// extraction purposes
struct Learningmotors_Pb_Macros_SlotName {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Display-friendly string also used as the default means of invoking this intent
  /// *required*
  var value: String = String()

  /// List of aliases that can be used for invocation. i.e. (value='History of Present Illness' then aliases=['hpi'])
  var aliases: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Learningmotors_Pb_Macros_MigrateSlateRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "learningmotors.pb.macros"

extension Learningmotors_Pb_Macros_Macro: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Macro"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .standard(proto: "user_id"),
    4: .same(proto: "tags"),
    5: .same(proto: "blocks"),
    6: .standard(proto: "created_at"),
    7: .standard(proto: "updated_at"),
    8: .standard(proto: "deleted_at"),
    9: .same(proto: "specialties"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeSingularStringField(value: &self.userID)
      case 4: try decoder.decodeRepeatedMessageField(value: &self.tags)
      case 5: try decoder.decodeRepeatedMessageField(value: &self.blocks)
      case 6: try decoder.decodeSingularMessageField(value: &self._createdAt)
      case 7: try decoder.decodeSingularMessageField(value: &self._updatedAt)
      case 8: try decoder.decodeSingularMessageField(value: &self._deletedAt)
      case 9: try decoder.decodeRepeatedEnumField(value: &self.specialties)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 2)
    }
    if !self.tags.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tags, fieldNumber: 4)
    }
    if !self.blocks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.blocks, fieldNumber: 5)
    }
    if let v = self._createdAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }
    if let v = self._updatedAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }
    if let v = self._deletedAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }
    if !self.specialties.isEmpty {
      try visitor.visitPackedEnumField(value: self.specialties, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_Macro, rhs: Learningmotors_Pb_Macros_Macro) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.tags != rhs.tags {return false}
    if lhs.blocks != rhs.blocks {return false}
    if lhs._createdAt != rhs._createdAt {return false}
    if lhs._updatedAt != rhs._updatedAt {return false}
    if lhs._deletedAt != rhs._deletedAt {return false}
    if lhs.specialties != rhs.specialties {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_Block: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Block"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "section_id"),
    2: .same(proto: "content"),
    3: .same(proto: "fields"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.sectionID)
      case 2: try decoder.decodeSingularStringField(value: &self.content)
      case 3: try decoder.decodeRepeatedMessageField(value: &self.fields)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sectionID.isEmpty {
      try visitor.visitSingularStringField(value: self.sectionID, fieldNumber: 1)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularStringField(value: self.content, fieldNumber: 2)
    }
    if !self.fields.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.fields, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_Block, rhs: Learningmotors_Pb_Macros_Block) -> Bool {
    if lhs.sectionID != rhs.sectionID {return false}
    if lhs.content != rhs.content {return false}
    if lhs.fields != rhs.fields {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_Tag: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Tag"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .same(proto: "type"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._name)
      case 2: try decoder.decodeSingularEnumField(value: &self.type)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._name {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if self.type != .default {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_Tag, rhs: Learningmotors_Pb_Macros_Tag) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_Tag.TypeEnum: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "DEFAULT"),
    1: .same(proto: "MACRO_TYPE"),
    2: .same(proto: "MACRO_TAG"),
    3: .same(proto: "BLOCK_TAG"),
    4: .same(proto: "MACRO_NAME"),
  ]
}

extension Learningmotors_Pb_Macros_CopyMacroRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CopyMacroRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "id"),
    3: .standard(proto: "user_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeSingularStringField(value: &self.id)
      case 3: try decoder.decodeSingularStringField(value: &self.userID)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 2)
    }
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_CopyMacroRequest, rhs: Learningmotors_Pb_Macros_CopyMacroRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.id != rhs.id {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_CopyMacroResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CopyMacroResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "macro"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._macro)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._macro {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_CopyMacroResponse, rhs: Learningmotors_Pb_Macros_CopyMacroResponse) -> Bool {
    if lhs._macro != rhs._macro {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_CopyMacroBySpecialtiesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CopyMacroBySpecialtiesRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "specialties"),
    2: .standard(proto: "organization_id"),
    3: .standard(proto: "user_id"),
    4: .standard(proto: "default_to_new_section_ids"),
    5: .same(proto: "specialtiesNAFlag"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedEnumField(value: &self.specialties)
      case 2: try decoder.decodeSingularStringField(value: &self.organizationID)
      case 3: try decoder.decodeSingularStringField(value: &self.userID)
      case 4: try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.defaultToNewSectionIds)
      case 5: try decoder.decodeSingularBoolField(value: &self.specialtiesNaflag)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.specialties.isEmpty {
      try visitor.visitPackedEnumField(value: self.specialties, fieldNumber: 1)
    }
    if !self.organizationID.isEmpty {
      try visitor.visitSingularStringField(value: self.organizationID, fieldNumber: 2)
    }
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 3)
    }
    if !self.defaultToNewSectionIds.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.defaultToNewSectionIds, fieldNumber: 4)
    }
    if self.specialtiesNaflag != false {
      try visitor.visitSingularBoolField(value: self.specialtiesNaflag, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_CopyMacroBySpecialtiesRequest, rhs: Learningmotors_Pb_Macros_CopyMacroBySpecialtiesRequest) -> Bool {
    if lhs.specialties != rhs.specialties {return false}
    if lhs.organizationID != rhs.organizationID {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.defaultToNewSectionIds != rhs.defaultToNewSectionIds {return false}
    if lhs.specialtiesNaflag != rhs.specialtiesNaflag {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_CopyMacroBySpecialtiesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CopyMacroBySpecialtiesResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "count"),
    2: .same(proto: "ids"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self.count)
      case 2: try decoder.decodeRepeatedStringField(value: &self.ids)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.count != 0 {
      try visitor.visitSingularInt32Field(value: self.count, fieldNumber: 1)
    }
    if !self.ids.isEmpty {
      try visitor.visitRepeatedStringField(value: self.ids, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_CopyMacroBySpecialtiesResponse, rhs: Learningmotors_Pb_Macros_CopyMacroBySpecialtiesResponse) -> Bool {
    if lhs.count != rhs.count {return false}
    if lhs.ids != rhs.ids {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_CreateMacroRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateMacroRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "macro"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeSingularMessageField(value: &self._macro)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if let v = self._macro {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_CreateMacroRequest, rhs: Learningmotors_Pb_Macros_CreateMacroRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs._macro != rhs._macro {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_CreateMacroResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateMacroResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "macro"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._macro)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._macro {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_CreateMacroResponse, rhs: Learningmotors_Pb_Macros_CreateMacroResponse) -> Bool {
    if lhs._macro != rhs._macro {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_GetMacrosRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetMacrosRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "ids"),
    3: .standard(proto: "user_id"),
    4: .standard(proto: "include_fields"),
    5: .same(proto: "name"),
    6: .standard(proto: "page_request"),
    7: .same(proto: "specialties"),
    8: .same(proto: "specialtiesEmpty"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeRepeatedStringField(value: &self.ids)
      case 3: try decoder.decodeSingularStringField(value: &self.userID)
      case 4: try decoder.decodeSingularBoolField(value: &self.includeFields)
      case 5: try decoder.decodeSingularStringField(value: &self.name)
      case 6: try decoder.decodeSingularMessageField(value: &self._pageRequest)
      case 7: try decoder.decodeRepeatedEnumField(value: &self.specialties)
      case 8: try decoder.decodeSingularBoolField(value: &self.specialtiesEmpty)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.ids.isEmpty {
      try visitor.visitRepeatedStringField(value: self.ids, fieldNumber: 2)
    }
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 3)
    }
    if self.includeFields != false {
      try visitor.visitSingularBoolField(value: self.includeFields, fieldNumber: 4)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 5)
    }
    if let v = self._pageRequest {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }
    if !self.specialties.isEmpty {
      try visitor.visitPackedEnumField(value: self.specialties, fieldNumber: 7)
    }
    if self.specialtiesEmpty != false {
      try visitor.visitSingularBoolField(value: self.specialtiesEmpty, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_GetMacrosRequest, rhs: Learningmotors_Pb_Macros_GetMacrosRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.ids != rhs.ids {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.includeFields != rhs.includeFields {return false}
    if lhs.name != rhs.name {return false}
    if lhs._pageRequest != rhs._pageRequest {return false}
    if lhs.specialties != rhs.specialties {return false}
    if lhs.specialtiesEmpty != rhs.specialtiesEmpty {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_GetMacrosResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetMacrosResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "macros"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.macros)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.macros.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.macros, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_GetMacrosResponse, rhs: Learningmotors_Pb_Macros_GetMacrosResponse) -> Bool {
    if lhs.macros != rhs.macros {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_UpdateMacroRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateMacroRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "macro"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeSingularMessageField(value: &self._macro)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if let v = self._macro {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_UpdateMacroRequest, rhs: Learningmotors_Pb_Macros_UpdateMacroRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs._macro != rhs._macro {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_UpdateMacroResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateMacroResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "macro"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._macro)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._macro {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_UpdateMacroResponse, rhs: Learningmotors_Pb_Macros_UpdateMacroResponse) -> Bool {
    if lhs._macro != rhs._macro {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_DeleteMacrosRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeleteMacrosRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "ids"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeRepeatedStringField(value: &self.ids)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.ids.isEmpty {
      try visitor.visitRepeatedStringField(value: self.ids, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_DeleteMacrosRequest, rhs: Learningmotors_Pb_Macros_DeleteMacrosRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.ids != rhs.ids {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_SlotName: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SlotName"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "value"),
    2: .same(proto: "aliases"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.value)
      case 2: try decoder.decodeRepeatedStringField(value: &self.aliases)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 1)
    }
    if !self.aliases.isEmpty {
      try visitor.visitRepeatedStringField(value: self.aliases, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_SlotName, rhs: Learningmotors_Pb_Macros_SlotName) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.aliases != rhs.aliases {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Macros_MigrateSlateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MigrateSlateRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Macros_MigrateSlateRequest, rhs: Learningmotors_Pb_Macros_MigrateSlateRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
