// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: suki/pb/oauth/v1/vendor.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// OAuth vendor registry id. Shared by the public QnA stream
// (ResponseFailed.vendor on LOGIN_REQUIRED / FORBIDDEN), Gateway
// /v1/oauth/vendors/{slug}/… path selection, and the cluster-internal
// VendorTokenService. Not owned by ms-caas — CAAS is one consumer.
//
// HTTP path slug mapping:
//   VENDOR_UPTODATE → "uptodate"

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated enum Suki_Pb_Oauth_V1_Vendor: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case uptodate // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .uptodate
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .uptodate: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Suki_Pb_Oauth_V1_Vendor] = [
    .unspecified,
    .uptodate,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension Suki_Pb_Oauth_V1_Vendor: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0VENDOR_UNSPECIFIED\0\u{1}VENDOR_UPTODATE\0")
}
