// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: appointments.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// An individual appointment that would typically define a patient-doctor encounter
struct Learningmotors_Pb_Appointment {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unique identifier for this appointment
  var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  /// fhir_id representing an appointment's FHIR ID set by the emr system
  var fhirID: String {
    get {return _storage._fhirID}
    set {_uniqueStorage()._fhirID = newValue}
  }

  /// ID of the doctor (user) whose schedule this represents
  /// *required*
  var ownerID: String {
    get {return _storage._ownerID}
    set {_uniqueStorage()._ownerID = newValue}
  }

  /// ID of the patient being seen
  var patientID: String {
    get {return _storage._patientID}
    set {_uniqueStorage()._patientID = newValue}
  }

  /// Time appointment should start at
  var startsAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._startsAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._startsAt = newValue}
  }
  /// Returns true if `startsAt` has been explicitly set.
  var hasStartsAt: Bool {return _storage._startsAt != nil}
  /// Clears the value of `startsAt`. Subsequent reads from it will return its default value.
  mutating func clearStartsAt() {_uniqueStorage()._startsAt = nil}

  /// Time appointment should end at
  var endsAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._endsAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._endsAt = newValue}
  }
  /// Returns true if `endsAt` has been explicitly set.
  var hasEndsAt: Bool {return _storage._endsAt != nil}
  /// Clears the value of `endsAt`. Subsequent reads from it will return its default value.
  mutating func clearEndsAt() {_uniqueStorage()._endsAt = nil}

  /// Any special flag for the appointment
  var appointmentType: Learningmotors_Pb_Appointment.AppointmentType {
    get {return _storage._appointmentType}
    set {_uniqueStorage()._appointmentType = newValue}
  }

  /// Optional: Procedure scheduled for the patient
  var medicalProcedure: String {
    get {return _storage._medicalProcedure}
    set {_uniqueStorage()._medicalProcedure = newValue}
  }

  /// Reason patient made an appointment (i.e. "Cough", "Abdominal pain") or
  /// any other reason to see the patient/any additional notes
  var reason: String {
    get {return _storage._reason}
    set {_uniqueStorage()._reason = newValue}
  }

  /// emr id set by the emr system
  var emrID: String {
    get {return _storage._emrID}
    set {_uniqueStorage()._emrID = newValue}
  }

  /// emr_encounter_id representing an encounter set by the emr system
  var emrEncounterID: String {
    get {return _storage._emrEncounterID}
    set {_uniqueStorage()._emrEncounterID = newValue}
  }

  /// Status of the EMR encounter (open, closed, etc.)
  var emrEncounterStatus: Learningmotors_Pb_Appointment.EMREncounterStatus {
    get {return _storage._emrEncounterStatus}
    set {_uniqueStorage()._emrEncounterStatus = newValue}
  }

  /// fhir_encounter_id representing an encounter's FHIR ID set by the emr system
  var fhirEncounterID: String {
    get {return _storage._fhirEncounterID}
    set {_uniqueStorage()._fhirEncounterID = newValue}
  }

  /// emr_encounter_id representing an encounter's ID Type set by the emr system
  var fhirEncounterIDType: String {
    get {return _storage._fhirEncounterIDType}
    set {_uniqueStorage()._fhirEncounterIDType = newValue}
  }

  /// emr_department_id is the department id for the appointment which is set
  /// by the emr system
  var emrDepartmentID: String {
    get {return _storage._emrDepartmentID}
    set {_uniqueStorage()._emrDepartmentID = newValue}
  }

  /// appointment_location_id is the location for the appointment which is set by the emr system
  /// would be used in Cerner to match related encounter. Cerner's FHIR API doesn't have mapping between appointment and encounter
  var appointmentLocationID: String {
    get {return _storage._appointmentLocationID}
    set {_uniqueStorage()._appointmentLocationID = newValue}
  }

  /// emr_user_id is the user/provider id for the appointment which is set by the emr system
  /// required to store with appointment to identify emr user when a suki user is linked with multiple EMR users
  var emrUserID: String {
    get {return _storage._emrUserID}
    set {_uniqueStorage()._emrUserID = newValue}
  }

  /// An appointment may either have a prior note created by the emr system
  /// or a composition created by the user
  var noteIdentifier: OneOf_NoteIdentifier? {
    get {return _storage._noteIdentifier}
    set {_uniqueStorage()._noteIdentifier = newValue}
  }

  var compositionID: String {
    get {
      if case .compositionID(let v)? = _storage._noteIdentifier {return v}
      return String()
    }
    set {_uniqueStorage()._noteIdentifier = .compositionID(newValue)}
  }

  var noteID: String {
    get {
      if case .noteID(let v)? = _storage._noteIdentifier {return v}
      return String()
    }
    set {_uniqueStorage()._noteIdentifier = .noteID(newValue)}
  }

  /// Timestamp when this record was initially created
  var createdAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._createdAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  var hasCreatedAt: Bool {return _storage._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  mutating func clearCreatedAt() {_uniqueStorage()._createdAt = nil}

  /// Timestamp when this record was last updated
  var updatedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._updatedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._updatedAt = newValue}
  }
  /// Returns true if `updatedAt` has been explicitly set.
  var hasUpdatedAt: Bool {return _storage._updatedAt != nil}
  /// Clears the value of `updatedAt`. Subsequent reads from it will return its default value.
  mutating func clearUpdatedAt() {_uniqueStorage()._updatedAt = nil}

  /// Timestamp when this record was flagged as deleted
  var deletedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._deletedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._deletedAt = newValue}
  }
  /// Returns true if `deletedAt` has been explicitly set.
  var hasDeletedAt: Bool {return _storage._deletedAt != nil}
  /// Clears the value of `deletedAt`. Subsequent reads from it will return its default value.
  mutating func clearDeletedAt() {_uniqueStorage()._deletedAt = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// An appointment may either have a prior note created by the emr system
  /// or a composition created by the user
  enum OneOf_NoteIdentifier: Equatable {
    case compositionID(String)
    case noteID(String)

  #if !swift(>=4.1)
    static func ==(lhs: Learningmotors_Pb_Appointment.OneOf_NoteIdentifier, rhs: Learningmotors_Pb_Appointment.OneOf_NoteIdentifier) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.compositionID, .compositionID): return {
        guard case .compositionID(let l) = lhs, case .compositionID(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.noteID, .noteID): return {
        guard case .noteID(let l) = lhs, case .noteID(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  enum AppointmentType: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case `default` // = 0

    /// New patient appointment
    case new // = 1

    /// Follow-up
    case followUp // = 2

    /// Pre-op
    case preOp // = 3

    /// Post-op
    case postOp // = 4

    /// This appointment came from an EHR encounter
    case ehrGenerated // = 5

    /// This appointment was created by a non-emr user and must be shown on schedule
    case nonEmrUserGenerated // = 6
    case UNRECOGNIZED(Int)

    init() {
      self = .default
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .default
      case 1: self = .new
      case 2: self = .followUp
      case 3: self = .preOp
      case 4: self = .postOp
      case 5: self = .ehrGenerated
      case 6: self = .nonEmrUserGenerated
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .default: return 0
      case .new: return 1
      case .followUp: return 2
      case .preOp: return 3
      case .postOp: return 4
      case .ehrGenerated: return 5
      case .nonEmrUserGenerated: return 6
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  enum EMREncounterStatus: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case unknown // = 0
    case `open` // = 1
    case closed // = 2
    case UNRECOGNIZED(Int)

    init() {
      self = .unknown
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unknown
      case 1: self = .open
      case 2: self = .closed
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unknown: return 0
      case .open: return 1
      case .closed: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=4.2)

extension Learningmotors_Pb_Appointment.AppointmentType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Learningmotors_Pb_Appointment.AppointmentType] = [
    .default,
    .new,
    .followUp,
    .preOp,
    .postOp,
    .ehrGenerated,
    .nonEmrUserGenerated,
  ]
}

extension Learningmotors_Pb_Appointment.EMREncounterStatus: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Learningmotors_Pb_Appointment.EMREncounterStatus] = [
    .unknown,
    .open,
    .closed,
  ]
}

#endif  // swift(>=4.2)

/// TODO: Deprecate this: This will be replaced by GetAppointmentsFromEMRRequest
/// Request for GetAppointments
/// Required: scope and either owner_id, ids, or emr_encounter_ids. The other filters are optional.
struct Learningmotors_Pb_GetAppointmentsRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// If specified, filter by doctor/user ID
  var ownerID: String = String()

  /// The start time of the appointment (Appointment.starts_at) should fall within the range specified here
  /// E.g.: If an appointment is from 1P-2P and the range here is 1P-1.30P then this appointment qualifies since the
  /// start time is falling in the range. The end time of the appointment is irrelevant.
  var startsAtRangeBeginning: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _startsAtRangeBeginning ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_startsAtRangeBeginning = newValue}
  }
  /// Returns true if `startsAtRangeBeginning` has been explicitly set.
  var hasStartsAtRangeBeginning: Bool {return self._startsAtRangeBeginning != nil}
  /// Clears the value of `startsAtRangeBeginning`. Subsequent reads from it will return its default value.
  mutating func clearStartsAtRangeBeginning() {self._startsAtRangeBeginning = nil}

  var startsAtRangeEnd: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _startsAtRangeEnd ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_startsAtRangeEnd = newValue}
  }
  /// Returns true if `startsAtRangeEnd` has been explicitly set.
  var hasStartsAtRangeEnd: Bool {return self._startsAtRangeEnd != nil}
  /// Clears the value of `startsAtRangeEnd`. Subsequent reads from it will return its default value.
  mutating func clearStartsAtRangeEnd() {self._startsAtRangeEnd = nil}

  /// If specified, filter by patient ID
  var patientID: String = String()

  /// If specified, filter by appointment ID
  var ids: [String] = []

  /// Scope of the appointments to get
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// If specified, filter by emr encounter ID
  var emrEncounterIds: [String] = []

  /// If specified, filter by emr appointment ID
  var emrIds: [String] = []

  /// If specified with value true, get suki generated (internal) appointments too
  var fetchInternalAppointments: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _startsAtRangeBeginning: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _startsAtRangeEnd: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

/// Response for GetAppointments
struct Learningmotors_Pb_GetAppointmentsResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var appointments: [Learningmotors_Pb_Appointment] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// GetAppointmentFromEMRRequest is a request to fetch schedules from an EMR
struct Learningmotors_Pb_GetAppointmentFromEMRRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// If specified, filter by doctor/user ID
  var ownerID: String = String()

  /// The start time of the appointment (Appointment.starts_at) should fall within the range specified here
  /// E.g.: If an appointment is from 1P-2P and the range here is 1P-1.30P then this appointment qualifies since the
  /// start time is falling in the range. The end time of the appointment is irrelevant.
  var startsAtRangeBeginning: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _startsAtRangeBeginning ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_startsAtRangeBeginning = newValue}
  }
  /// Returns true if `startsAtRangeBeginning` has been explicitly set.
  var hasStartsAtRangeBeginning: Bool {return self._startsAtRangeBeginning != nil}
  /// Clears the value of `startsAtRangeBeginning`. Subsequent reads from it will return its default value.
  mutating func clearStartsAtRangeBeginning() {self._startsAtRangeBeginning = nil}

  var startsAtRangeEnd: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _startsAtRangeEnd ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_startsAtRangeEnd = newValue}
  }
  /// Returns true if `startsAtRangeEnd` has been explicitly set.
  var hasStartsAtRangeEnd: Bool {return self._startsAtRangeEnd != nil}
  /// Clears the value of `startsAtRangeEnd`. Subsequent reads from it will return its default value.
  mutating func clearStartsAtRangeEnd() {self._startsAtRangeEnd = nil}

  /// If specified, filter by patient ID
  var patientID: String = String()

  /// If specified, filter by appointment ID
  var ids: [String] = []

  /// Scope of the appointments to get
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// If specified, filter by emr encounter ID
  var emrEncounterIds: [String] = []

  var source: Learningmotors_Pb_GetAppointmentFromEMRRequest.AppointmentSource = .pullFromDb

  /// optional field that may be used for efficient trigger-based schedule fetching
  var jobID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Specifies source for pulling appointments
  enum AppointmentSource: SwiftProtobuf.Enum {
    typealias RawValue = Int
    case pullFromDb // = 0
    case pullFromDbAndEmr // = 1
    case UNRECOGNIZED(Int)

    init() {
      self = .pullFromDb
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .pullFromDb
      case 1: self = .pullFromDbAndEmr
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .pullFromDb: return 0
      case .pullFromDbAndEmr: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  init() {}

  fileprivate var _startsAtRangeBeginning: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _startsAtRangeEnd: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

#if swift(>=4.2)

extension Learningmotors_Pb_GetAppointmentFromEMRRequest.AppointmentSource: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Learningmotors_Pb_GetAppointmentFromEMRRequest.AppointmentSource] = [
    .pullFromDb,
    .pullFromDbAndEmr,
  ]
}

#endif  // swift(>=4.2)

/// GetAppointmentFromEMRResponse is the response for trigger-based schedule fetching
struct Learningmotors_Pb_GetAppointmentFromEMRResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// a list of appointments sorted by start_time
  var appointments: [Learningmotors_Pb_Appointment] = []

  /// optional field that may be used for efficient trigger-based schedule fetching
  var jobID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Request for CreateOrUpdateAppointment
/// If Appointment.id field is present and existing, then we update the current appointment.
/// If Appointment.id field is not present, then we will create a new appointment with other Appointment.xx fields.
/// If Appointment.id field is existing but not valid, then we return error
struct Learningmotors_Pb_CreateOrUpdateAppointmentRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// *required*
  var appointment: Learningmotors_Pb_Appointment {
    get {return _appointment ?? Learningmotors_Pb_Appointment()}
    set {_appointment = newValue}
  }
  /// Returns true if `appointment` has been explicitly set.
  var hasAppointment: Bool {return self._appointment != nil}
  /// Clears the value of `appointment`. Subsequent reads from it will return its default value.
  mutating func clearAppointment() {self._appointment = nil}

  /// Scope of the appointment to create/update
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _appointment: Learningmotors_Pb_Appointment? = nil
  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

/// Response for CreateOrUpdateAppointment
struct Learningmotors_Pb_CreateOrUpdateAppointmentResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var appointment: Learningmotors_Pb_Appointment {
    get {return _appointment ?? Learningmotors_Pb_Appointment()}
    set {_appointment = newValue}
  }
  /// Returns true if `appointment` has been explicitly set.
  var hasAppointment: Bool {return self._appointment != nil}
  /// Clears the value of `appointment`. Subsequent reads from it will return its default value.
  mutating func clearAppointment() {self._appointment = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _appointment: Learningmotors_Pb_Appointment? = nil
}

/// Request for attaching/removing compoisition id from appointment
struct Learningmotors_Pb_UpdateAppointmentCompositionRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// *required* appointment ID to update
  var appointmentID: String = String()

  /// *required* organization ID to fetch appointment
  var organizationID: String = String()

  /// *required* composition ID to attach/remove from appointment
  var compositionID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Response of updated Appointment proto from composition ID attaching/removal
struct Learningmotors_Pb_UpdateAppointmentCompositionResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var appointment: Learningmotors_Pb_Appointment {
    get {return _appointment ?? Learningmotors_Pb_Appointment()}
    set {_appointment = newValue}
  }
  /// Returns true if `appointment` has been explicitly set.
  var hasAppointment: Bool {return self._appointment != nil}
  /// Clears the value of `appointment`. Subsequent reads from it will return its default value.
  mutating func clearAppointment() {self._appointment = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _appointment: Learningmotors_Pb_Appointment? = nil
}

/// Request for DeleteAppointments
/// You must supply either Suki IDs or EMR IDs (but not both).
struct Learningmotors_Pb_DeleteAppointmentsRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the appointments to delete
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// Suki IDs of appointments to delete
  var sukiIds: [String] = []

  /// EMR IDs of appointments to delete
  var emrIds: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

/// Gets the most recent appointment for a patient, can specify whether it has a emr appointment id or not
struct Learningmotors_Pb_GetMostRecentAppointmentRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  var sukiUserID: String = String()

  var sukiPatientID: String = String()

  var emrIDRequired: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

struct Learningmotors_Pb_GetMostRecentAppointmentResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var appointment: Learningmotors_Pb_Appointment {
    get {return _appointment ?? Learningmotors_Pb_Appointment()}
    set {_appointment = newValue}
  }
  /// Returns true if `appointment` has been explicitly set.
  var hasAppointment: Bool {return self._appointment != nil}
  /// Clears the value of `appointment`. Subsequent reads from it will return its default value.
  mutating func clearAppointment() {self._appointment = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _appointment: Learningmotors_Pb_Appointment? = nil
}

struct Learningmotors_Pb_BackfillAppointmentDataRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var startsAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _startsAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_startsAt = newValue}
  }
  /// Returns true if `startsAt` has been explicitly set.
  var hasStartsAt: Bool {return self._startsAt != nil}
  /// Clears the value of `startsAt`. Subsequent reads from it will return its default value.
  mutating func clearStartsAt() {self._startsAt = nil}

  var endsAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _endsAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_endsAt = newValue}
  }
  /// Returns true if `endsAt` has been explicitly set.
  var hasEndsAt: Bool {return self._endsAt != nil}
  /// Clears the value of `endsAt`. Subsequent reads from it will return its default value.
  mutating func clearEndsAt() {self._endsAt = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _startsAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _endsAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "learningmotors.pb"

extension Learningmotors_Pb_Appointment: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Appointment"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    21: .standard(proto: "fhir_id"),
    2: .standard(proto: "owner_id"),
    3: .standard(proto: "patient_id"),
    4: .standard(proto: "starts_at"),
    5: .standard(proto: "ends_at"),
    6: .standard(proto: "appointment_type"),
    7: .standard(proto: "medical_procedure"),
    8: .same(proto: "reason"),
    9: .standard(proto: "emr_id"),
    10: .standard(proto: "emr_encounter_id"),
    17: .standard(proto: "emr_encounter_status"),
    18: .standard(proto: "fhir_encounter_id"),
    19: .standard(proto: "fhir_encounter_id_type"),
    16: .standard(proto: "emr_department_id"),
    20: .standard(proto: "appointment_location_id"),
    22: .standard(proto: "emr_user_id"),
    11: .standard(proto: "composition_id"),
    12: .standard(proto: "note_id"),
    13: .standard(proto: "created_at"),
    14: .standard(proto: "updated_at"),
    15: .standard(proto: "deleted_at"),
  ]

  fileprivate class _StorageClass {
    var _id: String = String()
    var _fhirID: String = String()
    var _ownerID: String = String()
    var _patientID: String = String()
    var _startsAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _endsAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _appointmentType: Learningmotors_Pb_Appointment.AppointmentType = .default
    var _medicalProcedure: String = String()
    var _reason: String = String()
    var _emrID: String = String()
    var _emrEncounterID: String = String()
    var _emrEncounterStatus: Learningmotors_Pb_Appointment.EMREncounterStatus = .unknown
    var _fhirEncounterID: String = String()
    var _fhirEncounterIDType: String = String()
    var _emrDepartmentID: String = String()
    var _appointmentLocationID: String = String()
    var _emrUserID: String = String()
    var _noteIdentifier: Learningmotors_Pb_Appointment.OneOf_NoteIdentifier?
    var _createdAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _updatedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _deletedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _fhirID = source._fhirID
      _ownerID = source._ownerID
      _patientID = source._patientID
      _startsAt = source._startsAt
      _endsAt = source._endsAt
      _appointmentType = source._appointmentType
      _medicalProcedure = source._medicalProcedure
      _reason = source._reason
      _emrID = source._emrID
      _emrEncounterID = source._emrEncounterID
      _emrEncounterStatus = source._emrEncounterStatus
      _fhirEncounterID = source._fhirEncounterID
      _fhirEncounterIDType = source._fhirEncounterIDType
      _emrDepartmentID = source._emrDepartmentID
      _appointmentLocationID = source._appointmentLocationID
      _emrUserID = source._emrUserID
      _noteIdentifier = source._noteIdentifier
      _createdAt = source._createdAt
      _updatedAt = source._updatedAt
      _deletedAt = source._deletedAt
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._ownerID) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._patientID) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._startsAt) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._endsAt) }()
        case 6: try { try decoder.decodeSingularEnumField(value: &_storage._appointmentType) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._medicalProcedure) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._reason) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._emrID) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._emrEncounterID) }()
        case 11: try {
          var v: String?
          try decoder.decodeSingularStringField(value: &v)
          if let v = v {
            if _storage._noteIdentifier != nil {try decoder.handleConflictingOneOf()}
            _storage._noteIdentifier = .compositionID(v)
          }
        }()
        case 12: try {
          var v: String?
          try decoder.decodeSingularStringField(value: &v)
          if let v = v {
            if _storage._noteIdentifier != nil {try decoder.handleConflictingOneOf()}
            _storage._noteIdentifier = .noteID(v)
          }
        }()
        case 13: try { try decoder.decodeSingularMessageField(value: &_storage._createdAt) }()
        case 14: try { try decoder.decodeSingularMessageField(value: &_storage._updatedAt) }()
        case 15: try { try decoder.decodeSingularMessageField(value: &_storage._deletedAt) }()
        case 16: try { try decoder.decodeSingularStringField(value: &_storage._emrDepartmentID) }()
        case 17: try { try decoder.decodeSingularEnumField(value: &_storage._emrEncounterStatus) }()
        case 18: try { try decoder.decodeSingularStringField(value: &_storage._fhirEncounterID) }()
        case 19: try { try decoder.decodeSingularStringField(value: &_storage._fhirEncounterIDType) }()
        case 20: try { try decoder.decodeSingularStringField(value: &_storage._appointmentLocationID) }()
        case 21: try { try decoder.decodeSingularStringField(value: &_storage._fhirID) }()
        case 22: try { try decoder.decodeSingularStringField(value: &_storage._emrUserID) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._ownerID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._ownerID, fieldNumber: 2)
      }
      if !_storage._patientID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._patientID, fieldNumber: 3)
      }
      try { if let v = _storage._startsAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._endsAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if _storage._appointmentType != .default {
        try visitor.visitSingularEnumField(value: _storage._appointmentType, fieldNumber: 6)
      }
      if !_storage._medicalProcedure.isEmpty {
        try visitor.visitSingularStringField(value: _storage._medicalProcedure, fieldNumber: 7)
      }
      if !_storage._reason.isEmpty {
        try visitor.visitSingularStringField(value: _storage._reason, fieldNumber: 8)
      }
      if !_storage._emrID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._emrID, fieldNumber: 9)
      }
      if !_storage._emrEncounterID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._emrEncounterID, fieldNumber: 10)
      }
      switch _storage._noteIdentifier {
      case .compositionID?: try {
        guard case .compositionID(let v)? = _storage._noteIdentifier else { preconditionFailure() }
        try visitor.visitSingularStringField(value: v, fieldNumber: 11)
      }()
      case .noteID?: try {
        guard case .noteID(let v)? = _storage._noteIdentifier else { preconditionFailure() }
        try visitor.visitSingularStringField(value: v, fieldNumber: 12)
      }()
      case nil: break
      }
      try { if let v = _storage._createdAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._updatedAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._deletedAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
      } }()
      if !_storage._emrDepartmentID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._emrDepartmentID, fieldNumber: 16)
      }
      if _storage._emrEncounterStatus != .unknown {
        try visitor.visitSingularEnumField(value: _storage._emrEncounterStatus, fieldNumber: 17)
      }
      if !_storage._fhirEncounterID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fhirEncounterID, fieldNumber: 18)
      }
      if !_storage._fhirEncounterIDType.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fhirEncounterIDType, fieldNumber: 19)
      }
      if !_storage._appointmentLocationID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._appointmentLocationID, fieldNumber: 20)
      }
      if !_storage._fhirID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fhirID, fieldNumber: 21)
      }
      if !_storage._emrUserID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._emrUserID, fieldNumber: 22)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_Appointment, rhs: Learningmotors_Pb_Appointment) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._fhirID != rhs_storage._fhirID {return false}
        if _storage._ownerID != rhs_storage._ownerID {return false}
        if _storage._patientID != rhs_storage._patientID {return false}
        if _storage._startsAt != rhs_storage._startsAt {return false}
        if _storage._endsAt != rhs_storage._endsAt {return false}
        if _storage._appointmentType != rhs_storage._appointmentType {return false}
        if _storage._medicalProcedure != rhs_storage._medicalProcedure {return false}
        if _storage._reason != rhs_storage._reason {return false}
        if _storage._emrID != rhs_storage._emrID {return false}
        if _storage._emrEncounterID != rhs_storage._emrEncounterID {return false}
        if _storage._emrEncounterStatus != rhs_storage._emrEncounterStatus {return false}
        if _storage._fhirEncounterID != rhs_storage._fhirEncounterID {return false}
        if _storage._fhirEncounterIDType != rhs_storage._fhirEncounterIDType {return false}
        if _storage._emrDepartmentID != rhs_storage._emrDepartmentID {return false}
        if _storage._appointmentLocationID != rhs_storage._appointmentLocationID {return false}
        if _storage._emrUserID != rhs_storage._emrUserID {return false}
        if _storage._noteIdentifier != rhs_storage._noteIdentifier {return false}
        if _storage._createdAt != rhs_storage._createdAt {return false}
        if _storage._updatedAt != rhs_storage._updatedAt {return false}
        if _storage._deletedAt != rhs_storage._deletedAt {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_Appointment.AppointmentType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "DEFAULT"),
    1: .same(proto: "NEW"),
    2: .same(proto: "FOLLOW_UP"),
    3: .same(proto: "PRE_OP"),
    4: .same(proto: "POST_OP"),
    5: .same(proto: "EHR_GENERATED"),
    6: .same(proto: "NON_EMR_USER_GENERATED"),
  ]
}

extension Learningmotors_Pb_Appointment.EMREncounterStatus: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "UNKNOWN"),
    1: .same(proto: "OPEN"),
    2: .same(proto: "CLOSED"),
  ]
}

extension Learningmotors_Pb_GetAppointmentsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetAppointmentsRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "owner_id"),
    2: .standard(proto: "starts_at_range_beginning"),
    3: .standard(proto: "starts_at_range_end"),
    4: .standard(proto: "patient_id"),
    5: .same(proto: "ids"),
    6: .same(proto: "scope"),
    7: .standard(proto: "emr_encounter_ids"),
    8: .standard(proto: "emr_ids"),
    9: .standard(proto: "fetch_internal_appointments"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.ownerID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._startsAtRangeBeginning) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._startsAtRangeEnd) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.patientID) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.ids) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._scope) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.emrEncounterIds) }()
      case 8: try { try decoder.decodeRepeatedStringField(value: &self.emrIds) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.fetchInternalAppointments) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.ownerID.isEmpty {
      try visitor.visitSingularStringField(value: self.ownerID, fieldNumber: 1)
    }
    try { if let v = self._startsAtRangeBeginning {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._startsAtRangeEnd {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.patientID.isEmpty {
      try visitor.visitSingularStringField(value: self.patientID, fieldNumber: 4)
    }
    if !self.ids.isEmpty {
      try visitor.visitRepeatedStringField(value: self.ids, fieldNumber: 5)
    }
    try { if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    if !self.emrEncounterIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.emrEncounterIds, fieldNumber: 7)
    }
    if !self.emrIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.emrIds, fieldNumber: 8)
    }
    if self.fetchInternalAppointments != false {
      try visitor.visitSingularBoolField(value: self.fetchInternalAppointments, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_GetAppointmentsRequest, rhs: Learningmotors_Pb_GetAppointmentsRequest) -> Bool {
    if lhs.ownerID != rhs.ownerID {return false}
    if lhs._startsAtRangeBeginning != rhs._startsAtRangeBeginning {return false}
    if lhs._startsAtRangeEnd != rhs._startsAtRangeEnd {return false}
    if lhs.patientID != rhs.patientID {return false}
    if lhs.ids != rhs.ids {return false}
    if lhs._scope != rhs._scope {return false}
    if lhs.emrEncounterIds != rhs.emrEncounterIds {return false}
    if lhs.emrIds != rhs.emrIds {return false}
    if lhs.fetchInternalAppointments != rhs.fetchInternalAppointments {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_GetAppointmentsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetAppointmentsResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "appointments"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.appointments) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.appointments.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.appointments, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_GetAppointmentsResponse, rhs: Learningmotors_Pb_GetAppointmentsResponse) -> Bool {
    if lhs.appointments != rhs.appointments {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_GetAppointmentFromEMRRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetAppointmentFromEMRRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "owner_id"),
    2: .standard(proto: "starts_at_range_beginning"),
    3: .standard(proto: "starts_at_range_end"),
    4: .standard(proto: "patient_id"),
    5: .same(proto: "ids"),
    6: .same(proto: "scope"),
    7: .standard(proto: "emr_encounter_ids"),
    8: .same(proto: "source"),
    9: .standard(proto: "job_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.ownerID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._startsAtRangeBeginning) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._startsAtRangeEnd) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.patientID) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.ids) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._scope) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.emrEncounterIds) }()
      case 8: try { try decoder.decodeSingularEnumField(value: &self.source) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.jobID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.ownerID.isEmpty {
      try visitor.visitSingularStringField(value: self.ownerID, fieldNumber: 1)
    }
    try { if let v = self._startsAtRangeBeginning {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._startsAtRangeEnd {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.patientID.isEmpty {
      try visitor.visitSingularStringField(value: self.patientID, fieldNumber: 4)
    }
    if !self.ids.isEmpty {
      try visitor.visitRepeatedStringField(value: self.ids, fieldNumber: 5)
    }
    try { if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    if !self.emrEncounterIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.emrEncounterIds, fieldNumber: 7)
    }
    if self.source != .pullFromDb {
      try visitor.visitSingularEnumField(value: self.source, fieldNumber: 8)
    }
    if !self.jobID.isEmpty {
      try visitor.visitSingularStringField(value: self.jobID, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_GetAppointmentFromEMRRequest, rhs: Learningmotors_Pb_GetAppointmentFromEMRRequest) -> Bool {
    if lhs.ownerID != rhs.ownerID {return false}
    if lhs._startsAtRangeBeginning != rhs._startsAtRangeBeginning {return false}
    if lhs._startsAtRangeEnd != rhs._startsAtRangeEnd {return false}
    if lhs.patientID != rhs.patientID {return false}
    if lhs.ids != rhs.ids {return false}
    if lhs._scope != rhs._scope {return false}
    if lhs.emrEncounterIds != rhs.emrEncounterIds {return false}
    if lhs.source != rhs.source {return false}
    if lhs.jobID != rhs.jobID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_GetAppointmentFromEMRRequest.AppointmentSource: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "PULL_FROM_DB"),
    1: .same(proto: "PULL_FROM_DB_AND_EMR"),
  ]
}

extension Learningmotors_Pb_GetAppointmentFromEMRResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetAppointmentFromEMRResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "appointments"),
    2: .standard(proto: "job_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.appointments) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.jobID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.appointments.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.appointments, fieldNumber: 1)
    }
    if !self.jobID.isEmpty {
      try visitor.visitSingularStringField(value: self.jobID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_GetAppointmentFromEMRResponse, rhs: Learningmotors_Pb_GetAppointmentFromEMRResponse) -> Bool {
    if lhs.appointments != rhs.appointments {return false}
    if lhs.jobID != rhs.jobID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_CreateOrUpdateAppointmentRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateOrUpdateAppointmentRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "appointment"),
    2: .same(proto: "scope"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._appointment) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._scope) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._appointment {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_CreateOrUpdateAppointmentRequest, rhs: Learningmotors_Pb_CreateOrUpdateAppointmentRequest) -> Bool {
    if lhs._appointment != rhs._appointment {return false}
    if lhs._scope != rhs._scope {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_CreateOrUpdateAppointmentResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateOrUpdateAppointmentResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "appointment"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._appointment) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._appointment {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_CreateOrUpdateAppointmentResponse, rhs: Learningmotors_Pb_CreateOrUpdateAppointmentResponse) -> Bool {
    if lhs._appointment != rhs._appointment {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_UpdateAppointmentCompositionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateAppointmentCompositionRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "appointment_id"),
    2: .standard(proto: "organization_id"),
    3: .standard(proto: "composition_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.appointmentID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.organizationID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.compositionID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.appointmentID.isEmpty {
      try visitor.visitSingularStringField(value: self.appointmentID, fieldNumber: 1)
    }
    if !self.organizationID.isEmpty {
      try visitor.visitSingularStringField(value: self.organizationID, fieldNumber: 2)
    }
    if !self.compositionID.isEmpty {
      try visitor.visitSingularStringField(value: self.compositionID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_UpdateAppointmentCompositionRequest, rhs: Learningmotors_Pb_UpdateAppointmentCompositionRequest) -> Bool {
    if lhs.appointmentID != rhs.appointmentID {return false}
    if lhs.organizationID != rhs.organizationID {return false}
    if lhs.compositionID != rhs.compositionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_UpdateAppointmentCompositionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateAppointmentCompositionResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "appointment"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._appointment) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._appointment {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_UpdateAppointmentCompositionResponse, rhs: Learningmotors_Pb_UpdateAppointmentCompositionResponse) -> Bool {
    if lhs._appointment != rhs._appointment {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_DeleteAppointmentsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeleteAppointmentsRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .standard(proto: "suki_ids"),
    3: .standard(proto: "emr_ids"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._scope) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.sukiIds) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.emrIds) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.sukiIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.sukiIds, fieldNumber: 2)
    }
    if !self.emrIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.emrIds, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_DeleteAppointmentsRequest, rhs: Learningmotors_Pb_DeleteAppointmentsRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.sukiIds != rhs.sukiIds {return false}
    if lhs.emrIds != rhs.emrIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_GetMostRecentAppointmentRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetMostRecentAppointmentRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .standard(proto: "suki_user_id"),
    3: .standard(proto: "suki_patient_id"),
    4: .standard(proto: "emr_id_required"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._scope) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.sukiUserID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.sukiPatientID) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.emrIDRequired) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.sukiUserID.isEmpty {
      try visitor.visitSingularStringField(value: self.sukiUserID, fieldNumber: 2)
    }
    if !self.sukiPatientID.isEmpty {
      try visitor.visitSingularStringField(value: self.sukiPatientID, fieldNumber: 3)
    }
    if self.emrIDRequired != false {
      try visitor.visitSingularBoolField(value: self.emrIDRequired, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_GetMostRecentAppointmentRequest, rhs: Learningmotors_Pb_GetMostRecentAppointmentRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.sukiUserID != rhs.sukiUserID {return false}
    if lhs.sukiPatientID != rhs.sukiPatientID {return false}
    if lhs.emrIDRequired != rhs.emrIDRequired {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_GetMostRecentAppointmentResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetMostRecentAppointmentResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "appointment"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._appointment) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._appointment {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_GetMostRecentAppointmentResponse, rhs: Learningmotors_Pb_GetMostRecentAppointmentResponse) -> Bool {
    if lhs._appointment != rhs._appointment {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_BackfillAppointmentDataRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BackfillAppointmentDataRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "starts_at"),
    2: .standard(proto: "ends_at"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._startsAt) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._endsAt) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._startsAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._endsAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_BackfillAppointmentDataRequest, rhs: Learningmotors_Pb_BackfillAppointmentDataRequest) -> Bool {
    if lhs._startsAt != rhs._startsAt {return false}
    if lhs._endsAt != rhs._endsAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
