// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: suki/pb/recording/recording.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Recording represents a single recording file
nonisolated struct Suki_Pb_Recording_Recording: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unique identifier for this recording.
  /// Online sessions: SSP session ID. Offline sessions: Ambient session ID.
  var recordingID: String = String()

  /// Presigned URL to download or stream the recording
  var presignedURL: String = String()

  /// Unix timestamp (seconds) when the presigned URL expires
  var expiresAt: Int64 = 0

  /// Order of this recording within the session (1-indexed).
  /// Always 1 for offline sessions. May be >1 for online sessions with multiple recordings.
  var sequenceNumber: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// GetRecordingRequest is the request to get recordings for an ambient session
nonisolated struct Suki_Pb_Recording_GetRecordingRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unique ID of the ambient session
  var ambientSessionID: String = String()

  /// If true, returns download URL. If false (default), returns streaming URL with Range support.
  var download: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// GetRecordingResponse contains the list of recordings for the session
nonisolated struct Suki_Pb_Recording_GetRecordingResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of recordings (multiple for online sessions, single for offline)
  var recordings: [Suki_Pb_Recording_Recording] = []

  /// If true, URLs support streaming with Range requests. If false, URLs are download-only.
  /// Applies to all recordings in the response.
  var isStreamable: Bool = false

  /// Internal HTTP response metadata (not exposed to external clients)
  var httpResponseMetadata: Learningmotors_Pb_Common_HTTPResponseMetadata {
    get {_httpResponseMetadata ?? Learningmotors_Pb_Common_HTTPResponseMetadata()}
    set {_httpResponseMetadata = newValue}
  }
  /// Returns true if `httpResponseMetadata` has been explicitly set.
  var hasHTTPResponseMetadata: Bool {self._httpResponseMetadata != nil}
  /// Clears the value of `httpResponseMetadata`. Subsequent reads from it will return its default value.
  mutating func clearHTTPResponseMetadata() {self._httpResponseMetadata = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _httpResponseMetadata: Learningmotors_Pb_Common_HTTPResponseMetadata? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "suki.pb.recording"

nonisolated extension Suki_Pb_Recording_Recording: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Recording"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}recording_id\0\u{3}presigned_url\0\u{3}expires_at\0\u{3}sequence_number\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.recordingID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.presignedURL) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.expiresAt) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.sequenceNumber) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.recordingID.isEmpty {
      try visitor.visitSingularStringField(value: self.recordingID, fieldNumber: 1)
    }
    if !self.presignedURL.isEmpty {
      try visitor.visitSingularStringField(value: self.presignedURL, fieldNumber: 2)
    }
    if self.expiresAt != 0 {
      try visitor.visitSingularInt64Field(value: self.expiresAt, fieldNumber: 3)
    }
    if self.sequenceNumber != 0 {
      try visitor.visitSingularInt32Field(value: self.sequenceNumber, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Recording_Recording, rhs: Suki_Pb_Recording_Recording) -> Bool {
    if lhs.recordingID != rhs.recordingID {return false}
    if lhs.presignedURL != rhs.presignedURL {return false}
    if lhs.expiresAt != rhs.expiresAt {return false}
    if lhs.sequenceNumber != rhs.sequenceNumber {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Recording_GetRecordingRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetRecordingRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}ambient_session_id\0\u{1}download\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.ambientSessionID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.download) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ambientSessionID.isEmpty {
      try visitor.visitSingularStringField(value: self.ambientSessionID, fieldNumber: 1)
    }
    if self.download != false {
      try visitor.visitSingularBoolField(value: self.download, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Recording_GetRecordingRequest, rhs: Suki_Pb_Recording_GetRecordingRequest) -> Bool {
    if lhs.ambientSessionID != rhs.ambientSessionID {return false}
    if lhs.download != rhs.download {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Recording_GetRecordingResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetRecordingResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}recordings\0\u{3}is_streamable\0\u{4}b\u{1}http_response_metadata\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.recordings) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isStreamable) }()
      case 100: try { try decoder.decodeSingularMessageField(value: &self._httpResponseMetadata) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.recordings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.recordings, fieldNumber: 1)
    }
    if self.isStreamable != false {
      try visitor.visitSingularBoolField(value: self.isStreamable, fieldNumber: 2)
    }
    try { if let v = self._httpResponseMetadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 100)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Recording_GetRecordingResponse, rhs: Suki_Pb_Recording_GetRecordingResponse) -> Bool {
    if lhs.recordings != rhs.recordings {return false}
    if lhs.isStreamable != rhs.isStreamable {return false}
    if lhs._httpResponseMetadata != rhs._httpResponseMetadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
