//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: suki/pb/voice/mic.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Suki_Pb_Voice_MicClient`, then call methods of this protocol to make API calls.
internal protocol Suki_Pb_Voice_MicClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Suki_Pb_Voice_MicClientInterceptorFactoryProtocol? { get }

  func getTarget(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions?
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Suki_Pb_Voice_GetTargetResponse>

  func mic(
    callOptions: CallOptions?,
    handler: @escaping (Suki_Pb_Voice_MicResponse) -> Void
  ) -> BidirectionalStreamingCall<Suki_Pb_Voice_MicRequest, Suki_Pb_Voice_MicResponse>

  func audioStream(
    callOptions: CallOptions?,
    handler: @escaping (Suki_Pb_Voice_MicResponse) -> Void
  ) -> BidirectionalStreamingCall<Suki_Pb_Voice_MicRequest, Suki_Pb_Voice_MicResponse>

  func sendNoteType(
    _ request: Suki_Pb_Voice_NoteType,
    callOptions: CallOptions?
  ) -> UnaryCall<Suki_Pb_Voice_NoteType, SwiftProtobuf.Google_Protobuf_Empty>
}

extension Suki_Pb_Voice_MicClientProtocol {
  internal var serviceName: String {
    return "suki.pb.voice.Mic"
  }

  /// Unary RPC used by clients to obtain suki_target to be passed in metadata of
  /// subsequent requests.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetTarget.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getTarget(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Suki_Pb_Voice_GetTargetResponse> {
    return self.makeUnaryCall(
      path: "/suki.pb.voice.Mic/GetTarget",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetTargetInterceptors() ?? []
    )
  }

  /// Bidirectional RPC used by mobile client to connect as mic to backend.
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  internal func mic(
    callOptions: CallOptions? = nil,
    handler: @escaping (Suki_Pb_Voice_MicResponse) -> Void
  ) -> BidirectionalStreamingCall<Suki_Pb_Voice_MicRequest, Suki_Pb_Voice_MicResponse> {
    return self.makeBidirectionalStreamingCall(
      path: "/suki.pb.voice.Mic/Mic",
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeMicInterceptors() ?? [],
      handler: handler
    )
  }

  /// Bidirectional RPC used by mobile client for payattention feature
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  internal func audioStream(
    callOptions: CallOptions? = nil,
    handler: @escaping (Suki_Pb_Voice_MicResponse) -> Void
  ) -> BidirectionalStreamingCall<Suki_Pb_Voice_MicRequest, Suki_Pb_Voice_MicResponse> {
    return self.makeBidirectionalStreamingCall(
      path: "/suki.pb.voice.Mic/AudioStream",
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAudioStreamInterceptors() ?? [],
      handler: handler
    )
  }

  /// Unary RPC used by mobile client to send the type of Note in second screed of payattention feature
  ///
  /// - Parameters:
  ///   - request: Request to send to SendNoteType.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func sendNoteType(
    _ request: Suki_Pb_Voice_NoteType,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Suki_Pb_Voice_NoteType, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: "/suki.pb.voice.Mic/SendNoteType",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSendNoteTypeInterceptors() ?? []
    )
  }
}

internal protocol Suki_Pb_Voice_MicClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'getTarget'.
  func makeGetTargetInterceptors() -> [ClientInterceptor<SwiftProtobuf.Google_Protobuf_Empty, Suki_Pb_Voice_GetTargetResponse>]

  /// - Returns: Interceptors to use when invoking 'mic'.
  func makeMicInterceptors() -> [ClientInterceptor<Suki_Pb_Voice_MicRequest, Suki_Pb_Voice_MicResponse>]

  /// - Returns: Interceptors to use when invoking 'audioStream'.
  func makeAudioStreamInterceptors() -> [ClientInterceptor<Suki_Pb_Voice_MicRequest, Suki_Pb_Voice_MicResponse>]

  /// - Returns: Interceptors to use when invoking 'sendNoteType'.
  func makeSendNoteTypeInterceptors() -> [ClientInterceptor<Suki_Pb_Voice_NoteType, SwiftProtobuf.Google_Protobuf_Empty>]
}

internal final class Suki_Pb_Voice_MicClient: Suki_Pb_Voice_MicClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Suki_Pb_Voice_MicClientInterceptorFactoryProtocol?

  /// Creates a client for the suki.pb.voice.Mic service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Suki_Pb_Voice_MicClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

