//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: suki/pb/s2/s2.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// S2 is the service that connects the client to the suki backend
///
/// Usage: instantiate `Suki_Pb_S2_S2_StreamerClient`, then call methods of this protocol to make API calls.
internal protocol Suki_Pb_S2_S2_StreamerClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Suki_Pb_S2_S2_StreamerClientInterceptorFactoryProtocol? { get }

  func pingPong(
    _ request: Suki_Pb_S2_PingRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Suki_Pb_S2_PingRequest, Suki_Pb_S2_PongReply>

  func dialog(
    callOptions: CallOptions?,
    handler: @escaping (Suki_Pb_S2_DialogResponse) -> Void
  ) -> BidirectionalStreamingCall<Suki_Pb_S2_DialogRequest, Suki_Pb_S2_DialogResponse>
}

extension Suki_Pb_S2_S2_StreamerClientProtocol {
  internal var serviceName: String {
    return "suki.pb.s2.S2_Streamer"
  }

  /// Ping will serve as the health check between client and ms-s2 connection
  ///
  /// - Parameters:
  ///   - request: Request to send to PingPong.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func pingPong(
    _ request: Suki_Pb_S2_PingRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Suki_Pb_S2_PingRequest, Suki_Pb_S2_PongReply> {
    return self.makeUnaryCall(
      path: "/suki.pb.s2.S2_Streamer/PingPong",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePingPongInterceptors() ?? []
    )
  }

  /// Dialog is the bi-directional stream between ms-s2 and the client
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  internal func dialog(
    callOptions: CallOptions? = nil,
    handler: @escaping (Suki_Pb_S2_DialogResponse) -> Void
  ) -> BidirectionalStreamingCall<Suki_Pb_S2_DialogRequest, Suki_Pb_S2_DialogResponse> {
    return self.makeBidirectionalStreamingCall(
      path: "/suki.pb.s2.S2_Streamer/Dialog",
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDialogInterceptors() ?? [],
      handler: handler
    )
  }
}

internal protocol Suki_Pb_S2_S2_StreamerClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'pingPong'.
  func makePingPongInterceptors() -> [ClientInterceptor<Suki_Pb_S2_PingRequest, Suki_Pb_S2_PongReply>]

  /// - Returns: Interceptors to use when invoking 'dialog'.
  func makeDialogInterceptors() -> [ClientInterceptor<Suki_Pb_S2_DialogRequest, Suki_Pb_S2_DialogResponse>]
}

internal final class Suki_Pb_S2_S2_StreamerClient: Suki_Pb_S2_S2_StreamerClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Suki_Pb_S2_S2_StreamerClientInterceptorFactoryProtocol?

  /// Creates a client for the suki.pb.s2.S2_Streamer service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Suki_Pb_S2_S2_StreamerClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

