// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: learningmotors/pb/user/user.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Specialty
enum Learningmotors_Pb_User_Specialty: SwiftProtobuf.Enum {
  typealias RawValue = Int

  /// N/A - Demo User
  case na // = 0

  /// Allergy and Immunology
  case allergyAndImmunology // = 1

  /// Anesthesiology
  case anesthesiology // = 2

  /// Cardiology
  case cardiology // = 3

  /// Critical Care
  case criticalCare // = 4

  /// Dermatology
  case dermatology // = 5

  /// Emergency Medicine
  case emergencyMedicine // = 6

  /// Endocrinology
  case endocrinology // = 7

  /// Family Medicine
  case familyMedicine // = 8

  /// Gastroenterology
  case gastroenterology // = 9

  /// Genetics
  case genetics // = 10

  /// Hematology
  case hematology // = 11

  /// Infectious Disease
  case infectiousDisease // = 12

  /// Internal Medicine
  case internalMedicine // = 13

  /// Medical Oncology
  case medicalOncology // = 14

  /// Nephrology
  case nephrology // = 15

  /// Neurology
  case neurology // = 16

  /// Neurosurgery
  case neurosurgery // = 17

  /// Nuclear Medicine
  case nuclearMedicine // = 18

  /// Obstetrics and Gynecology
  case obstetricsGynecology // = 19

  /// Ophthalmology
  case ophthalmology // = 20

  /// Orthopedic Surgery
  case orthopedicSurgery // = 21

  /// Otolaryngology - Head and Neck Surgery
  case otolaryngologyHeadAndNeck // = 22

  /// Palliative Medicine
  case palliativeMedicine // = 23

  /// Pain Management
  case painManagement // = 24

  /// Pathology
  case pathology // = 25

  /// Pediatrics
  case pediatrics // = 26

  /// Physical Medicine and Rehabilitation
  case physicalMedicineAndRehabilitation // = 27

  /// Plastic Surgery
  case plasticSurgery // = 28

  /// Podiatry
  case podiatry // = 29

  /// Preventative Medicine
  case preventativeMedicine // = 30

  /// Psychiatry
  case psychiatry // = 31

  /// Pulmonology
  case pulmonology // = 32

  /// Radiation Oncology
  case radiationOncology // = 33

  /// Radiology - Diagnostic
  case radiologyDiagnostic // = 34

  /// Radiology - Interventional
  case radiologyInterventional // = 35

  /// Rheumatology
  case rheumatology // = 36

  /// Sports Medicine
  case sportsMedicine // = 37

  /// Surgery - Cardiac and Thoracic
  case surgeryCardiacAndThoracic // = 38

  /// Surgery - Colon and Rectal
  case surgeryColonAndRectal // = 39

  /// Surgery - General
  case surgeryGeneral // = 40

  /// Surgery - Pediatric
  case surgeryPediatric // = 41

  /// Surgery - Vascular
  case surgeryVascular // = 42

  /// Urology
  case urology // = 43

  /// Unlisted - Medical
  case unlistedMedical // = 44

  /// Unlisted - Surgical
  case unlistedSurgical // = 45
  case UNRECOGNIZED(Int)

  init() {
    self = .na
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .na
    case 1: self = .allergyAndImmunology
    case 2: self = .anesthesiology
    case 3: self = .cardiology
    case 4: self = .criticalCare
    case 5: self = .dermatology
    case 6: self = .emergencyMedicine
    case 7: self = .endocrinology
    case 8: self = .familyMedicine
    case 9: self = .gastroenterology
    case 10: self = .genetics
    case 11: self = .hematology
    case 12: self = .infectiousDisease
    case 13: self = .internalMedicine
    case 14: self = .medicalOncology
    case 15: self = .nephrology
    case 16: self = .neurology
    case 17: self = .neurosurgery
    case 18: self = .nuclearMedicine
    case 19: self = .obstetricsGynecology
    case 20: self = .ophthalmology
    case 21: self = .orthopedicSurgery
    case 22: self = .otolaryngologyHeadAndNeck
    case 23: self = .palliativeMedicine
    case 24: self = .painManagement
    case 25: self = .pathology
    case 26: self = .pediatrics
    case 27: self = .physicalMedicineAndRehabilitation
    case 28: self = .plasticSurgery
    case 29: self = .podiatry
    case 30: self = .preventativeMedicine
    case 31: self = .psychiatry
    case 32: self = .pulmonology
    case 33: self = .radiationOncology
    case 34: self = .radiologyDiagnostic
    case 35: self = .radiologyInterventional
    case 36: self = .rheumatology
    case 37: self = .sportsMedicine
    case 38: self = .surgeryCardiacAndThoracic
    case 39: self = .surgeryColonAndRectal
    case 40: self = .surgeryGeneral
    case 41: self = .surgeryPediatric
    case 42: self = .surgeryVascular
    case 43: self = .urology
    case 44: self = .unlistedMedical
    case 45: self = .unlistedSurgical
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .na: return 0
    case .allergyAndImmunology: return 1
    case .anesthesiology: return 2
    case .cardiology: return 3
    case .criticalCare: return 4
    case .dermatology: return 5
    case .emergencyMedicine: return 6
    case .endocrinology: return 7
    case .familyMedicine: return 8
    case .gastroenterology: return 9
    case .genetics: return 10
    case .hematology: return 11
    case .infectiousDisease: return 12
    case .internalMedicine: return 13
    case .medicalOncology: return 14
    case .nephrology: return 15
    case .neurology: return 16
    case .neurosurgery: return 17
    case .nuclearMedicine: return 18
    case .obstetricsGynecology: return 19
    case .ophthalmology: return 20
    case .orthopedicSurgery: return 21
    case .otolaryngologyHeadAndNeck: return 22
    case .palliativeMedicine: return 23
    case .painManagement: return 24
    case .pathology: return 25
    case .pediatrics: return 26
    case .physicalMedicineAndRehabilitation: return 27
    case .plasticSurgery: return 28
    case .podiatry: return 29
    case .preventativeMedicine: return 30
    case .psychiatry: return 31
    case .pulmonology: return 32
    case .radiationOncology: return 33
    case .radiologyDiagnostic: return 34
    case .radiologyInterventional: return 35
    case .rheumatology: return 36
    case .sportsMedicine: return 37
    case .surgeryCardiacAndThoracic: return 38
    case .surgeryColonAndRectal: return 39
    case .surgeryGeneral: return 40
    case .surgeryPediatric: return 41
    case .surgeryVascular: return 42
    case .urology: return 43
    case .unlistedMedical: return 44
    case .unlistedSurgical: return 45
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Learningmotors_Pb_User_Specialty: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Learningmotors_Pb_User_Specialty] = [
    .na,
    .allergyAndImmunology,
    .anesthesiology,
    .cardiology,
    .criticalCare,
    .dermatology,
    .emergencyMedicine,
    .endocrinology,
    .familyMedicine,
    .gastroenterology,
    .genetics,
    .hematology,
    .infectiousDisease,
    .internalMedicine,
    .medicalOncology,
    .nephrology,
    .neurology,
    .neurosurgery,
    .nuclearMedicine,
    .obstetricsGynecology,
    .ophthalmology,
    .orthopedicSurgery,
    .otolaryngologyHeadAndNeck,
    .palliativeMedicine,
    .painManagement,
    .pathology,
    .pediatrics,
    .physicalMedicineAndRehabilitation,
    .plasticSurgery,
    .podiatry,
    .preventativeMedicine,
    .psychiatry,
    .pulmonology,
    .radiationOncology,
    .radiologyDiagnostic,
    .radiologyInterventional,
    .rheumatology,
    .sportsMedicine,
    .surgeryCardiacAndThoracic,
    .surgeryColonAndRectal,
    .surgeryGeneral,
    .surgeryPediatric,
    .surgeryVascular,
    .urology,
    .unlistedMedical,
    .unlistedSurgical,
  ]
}

#endif  // swift(>=4.2)

/// Collection of attributes and profile information about a user.
/// A user is anyone who can login to the system and interact within Suki's UI.
/// This could be doctors, scribes, and admins who may partake in the system.
/// This does NOT include patients, who are defined separately and have their own associated service.
struct Learningmotors_Pb_User_User {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unique identifier assigned by User Service
  var id: String = String()

  /// User's roles (doctor, scribe, etc.)
  var roles: [Learningmotors_Pb_User_Role] = []

  /// Biographical information (first name, last name, etc.)
  var person: Learningmotors_Pb_Common_Person {
    get {return _person ?? Learningmotors_Pb_Common_Person()}
    set {_person = newValue}
  }
  /// Returns true if `person` has been explicitly set.
  var hasPerson: Bool {return self._person != nil}
  /// Clears the value of `person`. Subsequent reads from it will return its default value.
  mutating func clearPerson() {self._person = nil}

  /// ID assigned by authorization service (e.g. Okta)
  var authID: String = String()

  /// Email
  var email: String = String()

  /// Doctor specialty
  var specialty: String = String()

  /// IANA timezone (see the TZ column here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
  /// *required*
  var timezone: String = String()

  /// Timestamp when this record was initially created
  var createdAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _createdAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  var hasCreatedAt: Bool {return self._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  mutating func clearCreatedAt() {self._createdAt = nil}

  /// Timestamp when this record was last updated
  var updatedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _updatedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_updatedAt = newValue}
  }
  /// Returns true if `updatedAt` has been explicitly set.
  var hasUpdatedAt: Bool {return self._updatedAt != nil}
  /// Clears the value of `updatedAt`. Subsequent reads from it will return its default value.
  mutating func clearUpdatedAt() {self._updatedAt = nil}

  /// MD, MA, NP, PA, etc.
  var userType: String = String()

  /// Timestamp when an activation email was sent to the user
  var activationSent: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _activationSent ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_activationSent = newValue}
  }
  /// Returns true if `activationSent` has been explicitly set.
  var hasActivationSent: Bool {return self._activationSent != nil}
  /// Clears the value of `activationSent`. Subsequent reads from it will return its default value.
  mutating func clearActivationSent() {self._activationSent = nil}

  var organizationID: String = String()

  /// Specialties of user (if doctor)
  var specialties: [Learningmotors_Pb_User_Specialty] = []

  /// Timestamp at which user completed registration (self-onboarding)
  var registeredAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _registeredAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_registeredAt = newValue}
  }
  /// Returns true if `registeredAt` has been explicitly set.
  var hasRegisteredAt: Bool {return self._registeredAt != nil}
  /// Clears the value of `registeredAt`. Subsequent reads from it will return its default value.
  mutating func clearRegisteredAt() {self._registeredAt = nil}

  /// Phone number provided during onboarding
  var phoneNumber: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _person: Learningmotors_Pb_Common_Person? = nil
  fileprivate var _createdAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _updatedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _activationSent: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _registeredAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// Roles for a user (a user could be both a doctor and a scribe)
struct Learningmotors_Pb_User_Role {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Learningmotors_Pb_User_Role.RoleType = .noAccess

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum RoleType: SwiftProtobuf.Enum {
    typealias RawValue = Int

    /// User having no access to the product
    case noAccess // = 0

    /// User using the voice-agent
    case user // = 1

    /// Scribe/QA user
    case scribe // = 2

    /// Admin view user
    case admin // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .noAccess
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .noAccess
      case 1: self = .user
      case 2: self = .scribe
      case 3: self = .admin
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .noAccess: return 0
      case .user: return 1
      case .scribe: return 2
      case .admin: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  init() {}
}

#if swift(>=4.2)

extension Learningmotors_Pb_User_Role.RoleType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static var allCases: [Learningmotors_Pb_User_Role.RoleType] = [
    .noAccess,
    .user,
    .scribe,
    .admin,
  ]
}

#endif  // swift(>=4.2)

/// Request for Get
/// TODO: Add paging
struct Learningmotors_Pb_User_GetRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the users to get
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// IDs of users to retrieve
  var ids: [String] = []

  /// Flag for whether this is the initial fetch of User in a session
  var onLogin: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

/// Response for Get
struct Learningmotors_Pb_User_GetResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var users: [Learningmotors_Pb_User_User] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Request for Create
struct Learningmotors_Pb_User_CreateRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the user to create
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// *required*
  var user: Learningmotors_Pb_User_User {
    get {return _user ?? Learningmotors_Pb_User_User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  /// *optional*
  /// User's EMR if provided during self-onboarding
  var emr: Learningmotors_Pb_Emraccounts_EMRType = .unknown

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
  fileprivate var _user: Learningmotors_Pb_User_User? = nil
}

/// Request to send out a verification email to the user
struct Learningmotors_Pb_User_SendVerificationEmailRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// *required*
  var user: Learningmotors_Pb_User_User {
    get {return _user ?? Learningmotors_Pb_User_User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  /// *required*
  /// name of doctor's practice
  var practiceName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _user: Learningmotors_Pb_User_User? = nil
}

/// Request for validating a verification token
struct Learningmotors_Pb_User_ValidateVerificationTokenRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// *required*
  /// user's email
  var email: String = String()

  /// *required*
  /// token mailed to user
  var token: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Response for ValidateVerificationToken RPC
struct Learningmotors_Pb_User_ValidateVerificationTokenResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// user info
  var user: Learningmotors_Pb_User_User {
    get {return _user ?? Learningmotors_Pb_User_User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  /// name of medical practice
  var practiceName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _user: Learningmotors_Pb_User_User? = nil
}

/// Request to register and provision a user
struct Learningmotors_Pb_User_RegisterRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// *required*
  /// user info
  var user: Learningmotors_Pb_User_User {
    get {return _user ?? Learningmotors_Pb_User_User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  /// *required*
  /// verification token
  var token: String = String()

  /// *required* 
  /// password
  var password: String = String()

  /// user EMR
  var emr: Learningmotors_Pb_Emraccounts_EMRType = .unknown

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _user: Learningmotors_Pb_User_User? = nil
}

/// Response for Create
struct Learningmotors_Pb_User_CreateResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// id and auth_id will be set
  var user: Learningmotors_Pb_User_User {
    get {return _user ?? Learningmotors_Pb_User_User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _user: Learningmotors_Pb_User_User? = nil
}

/// Request for CreateWithPassword
struct Learningmotors_Pb_User_CreateWithPasswordRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the user to create
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// *required*
  var user: Learningmotors_Pb_User_User {
    get {return _user ?? Learningmotors_Pb_User_User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  /// *required*
  var password: String = String()

  /// *optional*
  var recoveryQuestions: [Suki_Pb_Accounts_PasswordRecoveryQuestion] = []

  /// *optional*
  /// User's EMR if provided during self-onboarding
  var emr: Learningmotors_Pb_Emraccounts_EMRType = .unknown

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
  fileprivate var _user: Learningmotors_Pb_User_User? = nil
}

/// Response for CreateWithPassword
struct Learningmotors_Pb_User_CreateWithPasswordResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// id and auth_id will be set
  var user: Learningmotors_Pb_User_User {
    get {return _user ?? Learningmotors_Pb_User_User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _user: Learningmotors_Pb_User_User? = nil
}

/// Request for Update
struct Learningmotors_Pb_User_UpdateRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the user to update
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// *required*
  var user: Learningmotors_Pb_User_User {
    get {return _user ?? Learningmotors_Pb_User_User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
  fileprivate var _user: Learningmotors_Pb_User_User? = nil
}

/// Response for Update
struct Learningmotors_Pb_User_UpdateResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var user: Learningmotors_Pb_User_User {
    get {return _user ?? Learningmotors_Pb_User_User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _user: Learningmotors_Pb_User_User? = nil
}

/// Request for Delete
struct Learningmotors_Pb_User_DeleteRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the users to delete
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// IDs of users to delete
  /// *required*
  var ids: [String] = []

  /// If true then the user is deleted in Okta permanently, removing them from all Suki environments
  /// in Okta. If false this will remove a user from the application in Okta that the deletion was initialized from.
  /// This should only be set true for testing. The default is false.
  var performHardDelete: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

/// Request for Activate
struct Learningmotors_Pb_User_ActivateRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the user to activate
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// ID of the user to activate
  /// *required*
  var id: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

struct Learningmotors_Pb_User_RegisterMarketplaceUserRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var user: Learningmotors_Pb_User_User {
    get {return _user ?? Learningmotors_Pb_User_User()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  /// Corresponds to the google account id
  var accountID: String = String()

  var password: String = String()

  var emr: Learningmotors_Pb_Emraccounts_EMRType = .unknown

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _user: Learningmotors_Pb_User_User? = nil
}

struct Learningmotors_Pb_User_RegisterMarketplaceUserResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The userId that was generated for this new user
  var userID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Learningmotors_Pb_User_SendGcpUsageMetricsRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Learningmotors_Pb_User_SendGcpUsageMetricsResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "learningmotors.pb.user"

extension Learningmotors_Pb_User_Specialty: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NA"),
    1: .same(proto: "ALLERGY_AND_IMMUNOLOGY"),
    2: .same(proto: "ANESTHESIOLOGY"),
    3: .same(proto: "CARDIOLOGY"),
    4: .same(proto: "CRITICAL_CARE"),
    5: .same(proto: "DERMATOLOGY"),
    6: .same(proto: "EMERGENCY_MEDICINE"),
    7: .same(proto: "ENDOCRINOLOGY"),
    8: .same(proto: "FAMILY_MEDICINE"),
    9: .same(proto: "GASTROENTEROLOGY"),
    10: .same(proto: "GENETICS"),
    11: .same(proto: "HEMATOLOGY"),
    12: .same(proto: "INFECTIOUS_DISEASE"),
    13: .same(proto: "INTERNAL_MEDICINE"),
    14: .same(proto: "MEDICAL_ONCOLOGY"),
    15: .same(proto: "NEPHROLOGY"),
    16: .same(proto: "NEUROLOGY"),
    17: .same(proto: "NEUROSURGERY"),
    18: .same(proto: "NUCLEAR_MEDICINE"),
    19: .same(proto: "OBSTETRICS_GYNECOLOGY"),
    20: .same(proto: "OPHTHALMOLOGY"),
    21: .same(proto: "ORTHOPEDIC_SURGERY"),
    22: .same(proto: "OTOLARYNGOLOGY_HEAD_AND_NECK"),
    23: .same(proto: "PALLIATIVE_MEDICINE"),
    24: .same(proto: "PAIN_MANAGEMENT"),
    25: .same(proto: "PATHOLOGY"),
    26: .same(proto: "PEDIATRICS"),
    27: .same(proto: "PHYSICAL_MEDICINE_AND_REHABILITATION"),
    28: .same(proto: "PLASTIC_SURGERY"),
    29: .same(proto: "PODIATRY"),
    30: .same(proto: "PREVENTATIVE_MEDICINE"),
    31: .same(proto: "PSYCHIATRY"),
    32: .same(proto: "PULMONOLOGY"),
    33: .same(proto: "RADIATION_ONCOLOGY"),
    34: .same(proto: "RADIOLOGY_DIAGNOSTIC"),
    35: .same(proto: "RADIOLOGY_INTERVENTIONAL"),
    36: .same(proto: "RHEUMATOLOGY"),
    37: .same(proto: "SPORTS_MEDICINE"),
    38: .same(proto: "SURGERY_CARDIAC_AND_THORACIC"),
    39: .same(proto: "SURGERY_COLON_AND_RECTAL"),
    40: .same(proto: "SURGERY_GENERAL"),
    41: .same(proto: "SURGERY_PEDIATRIC"),
    42: .same(proto: "SURGERY_VASCULAR"),
    43: .same(proto: "UROLOGY"),
    44: .same(proto: "UNLISTED_MEDICAL"),
    45: .same(proto: "UNLISTED_SURGICAL"),
  ]
}

extension Learningmotors_Pb_User_User: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".User"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "roles"),
    3: .same(proto: "person"),
    4: .standard(proto: "auth_id"),
    5: .same(proto: "email"),
    6: .same(proto: "specialty"),
    7: .same(proto: "timezone"),
    8: .standard(proto: "created_at"),
    9: .standard(proto: "updated_at"),
    10: .standard(proto: "user_type"),
    11: .standard(proto: "activation_sent"),
    12: .standard(proto: "organization_id"),
    13: .same(proto: "specialties"),
    14: .standard(proto: "registered_at"),
    15: .standard(proto: "phone_number"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.id)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.roles)
      case 3: try decoder.decodeSingularMessageField(value: &self._person)
      case 4: try decoder.decodeSingularStringField(value: &self.authID)
      case 5: try decoder.decodeSingularStringField(value: &self.email)
      case 6: try decoder.decodeSingularStringField(value: &self.specialty)
      case 7: try decoder.decodeSingularStringField(value: &self.timezone)
      case 8: try decoder.decodeSingularMessageField(value: &self._createdAt)
      case 9: try decoder.decodeSingularMessageField(value: &self._updatedAt)
      case 10: try decoder.decodeSingularStringField(value: &self.userType)
      case 11: try decoder.decodeSingularMessageField(value: &self._activationSent)
      case 12: try decoder.decodeSingularStringField(value: &self.organizationID)
      case 13: try decoder.decodeRepeatedEnumField(value: &self.specialties)
      case 14: try decoder.decodeSingularMessageField(value: &self._registeredAt)
      case 15: try decoder.decodeSingularStringField(value: &self.phoneNumber)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.roles.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.roles, fieldNumber: 2)
    }
    if let v = self._person {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }
    if !self.authID.isEmpty {
      try visitor.visitSingularStringField(value: self.authID, fieldNumber: 4)
    }
    if !self.email.isEmpty {
      try visitor.visitSingularStringField(value: self.email, fieldNumber: 5)
    }
    if !self.specialty.isEmpty {
      try visitor.visitSingularStringField(value: self.specialty, fieldNumber: 6)
    }
    if !self.timezone.isEmpty {
      try visitor.visitSingularStringField(value: self.timezone, fieldNumber: 7)
    }
    if let v = self._createdAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }
    if let v = self._updatedAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }
    if !self.userType.isEmpty {
      try visitor.visitSingularStringField(value: self.userType, fieldNumber: 10)
    }
    if let v = self._activationSent {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }
    if !self.organizationID.isEmpty {
      try visitor.visitSingularStringField(value: self.organizationID, fieldNumber: 12)
    }
    if !self.specialties.isEmpty {
      try visitor.visitPackedEnumField(value: self.specialties, fieldNumber: 13)
    }
    if let v = self._registeredAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
    }
    if !self.phoneNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.phoneNumber, fieldNumber: 15)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_User, rhs: Learningmotors_Pb_User_User) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.roles != rhs.roles {return false}
    if lhs._person != rhs._person {return false}
    if lhs.authID != rhs.authID {return false}
    if lhs.email != rhs.email {return false}
    if lhs.specialty != rhs.specialty {return false}
    if lhs.timezone != rhs.timezone {return false}
    if lhs._createdAt != rhs._createdAt {return false}
    if lhs._updatedAt != rhs._updatedAt {return false}
    if lhs.userType != rhs.userType {return false}
    if lhs._activationSent != rhs._activationSent {return false}
    if lhs.organizationID != rhs.organizationID {return false}
    if lhs.specialties != rhs.specialties {return false}
    if lhs._registeredAt != rhs._registeredAt {return false}
    if lhs.phoneNumber != rhs.phoneNumber {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_Role: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Role"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "type"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularEnumField(value: &self.type)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.type != .noAccess {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_Role, rhs: Learningmotors_Pb_User_Role) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_Role.RoleType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "NO_ACCESS"),
    1: .same(proto: "USER"),
    2: .same(proto: "SCRIBE"),
    3: .same(proto: "ADMIN"),
  ]
}

extension Learningmotors_Pb_User_GetRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "ids"),
    3: .standard(proto: "on_login"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeRepeatedStringField(value: &self.ids)
      case 3: try decoder.decodeSingularBoolField(value: &self.onLogin)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.ids.isEmpty {
      try visitor.visitRepeatedStringField(value: self.ids, fieldNumber: 2)
    }
    if self.onLogin != false {
      try visitor.visitSingularBoolField(value: self.onLogin, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_GetRequest, rhs: Learningmotors_Pb_User_GetRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.ids != rhs.ids {return false}
    if lhs.onLogin != rhs.onLogin {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_GetResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "users"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.users)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.users.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.users, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_GetResponse, rhs: Learningmotors_Pb_User_GetResponse) -> Bool {
    if lhs.users != rhs.users {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_CreateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "user"),
    3: .same(proto: "emr"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeSingularMessageField(value: &self._user)
      case 3: try decoder.decodeSingularEnumField(value: &self.emr)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    if self.emr != .unknown {
      try visitor.visitSingularEnumField(value: self.emr, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_CreateRequest, rhs: Learningmotors_Pb_User_CreateRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs._user != rhs._user {return false}
    if lhs.emr != rhs.emr {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_SendVerificationEmailRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SendVerificationEmailRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "user"),
    2: .standard(proto: "practice_name"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._user)
      case 2: try decoder.decodeSingularStringField(value: &self.practiceName)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.practiceName.isEmpty {
      try visitor.visitSingularStringField(value: self.practiceName, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_SendVerificationEmailRequest, rhs: Learningmotors_Pb_User_SendVerificationEmailRequest) -> Bool {
    if lhs._user != rhs._user {return false}
    if lhs.practiceName != rhs.practiceName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_ValidateVerificationTokenRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ValidateVerificationTokenRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "email"),
    2: .same(proto: "token"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.email)
      case 2: try decoder.decodeSingularStringField(value: &self.token)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.email.isEmpty {
      try visitor.visitSingularStringField(value: self.email, fieldNumber: 1)
    }
    if !self.token.isEmpty {
      try visitor.visitSingularStringField(value: self.token, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_ValidateVerificationTokenRequest, rhs: Learningmotors_Pb_User_ValidateVerificationTokenRequest) -> Bool {
    if lhs.email != rhs.email {return false}
    if lhs.token != rhs.token {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_ValidateVerificationTokenResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ValidateVerificationTokenResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "user"),
    2: .standard(proto: "practice_name"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._user)
      case 2: try decoder.decodeSingularStringField(value: &self.practiceName)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.practiceName.isEmpty {
      try visitor.visitSingularStringField(value: self.practiceName, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_ValidateVerificationTokenResponse, rhs: Learningmotors_Pb_User_ValidateVerificationTokenResponse) -> Bool {
    if lhs._user != rhs._user {return false}
    if lhs.practiceName != rhs.practiceName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_RegisterRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RegisterRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "user"),
    2: .same(proto: "token"),
    3: .same(proto: "password"),
    4: .same(proto: "emr"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._user)
      case 2: try decoder.decodeSingularStringField(value: &self.token)
      case 3: try decoder.decodeSingularStringField(value: &self.password)
      case 4: try decoder.decodeSingularEnumField(value: &self.emr)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.token.isEmpty {
      try visitor.visitSingularStringField(value: self.token, fieldNumber: 2)
    }
    if !self.password.isEmpty {
      try visitor.visitSingularStringField(value: self.password, fieldNumber: 3)
    }
    if self.emr != .unknown {
      try visitor.visitSingularEnumField(value: self.emr, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_RegisterRequest, rhs: Learningmotors_Pb_User_RegisterRequest) -> Bool {
    if lhs._user != rhs._user {return false}
    if lhs.token != rhs.token {return false}
    if lhs.password != rhs.password {return false}
    if lhs.emr != rhs.emr {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_CreateResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "user"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._user)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_CreateResponse, rhs: Learningmotors_Pb_User_CreateResponse) -> Bool {
    if lhs._user != rhs._user {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_CreateWithPasswordRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateWithPasswordRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "user"),
    3: .same(proto: "password"),
    4: .standard(proto: "recovery_questions"),
    5: .same(proto: "emr"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeSingularMessageField(value: &self._user)
      case 3: try decoder.decodeSingularStringField(value: &self.password)
      case 4: try decoder.decodeRepeatedMessageField(value: &self.recoveryQuestions)
      case 5: try decoder.decodeSingularEnumField(value: &self.emr)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    if !self.password.isEmpty {
      try visitor.visitSingularStringField(value: self.password, fieldNumber: 3)
    }
    if !self.recoveryQuestions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.recoveryQuestions, fieldNumber: 4)
    }
    if self.emr != .unknown {
      try visitor.visitSingularEnumField(value: self.emr, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_CreateWithPasswordRequest, rhs: Learningmotors_Pb_User_CreateWithPasswordRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs._user != rhs._user {return false}
    if lhs.password != rhs.password {return false}
    if lhs.recoveryQuestions != rhs.recoveryQuestions {return false}
    if lhs.emr != rhs.emr {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_CreateWithPasswordResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateWithPasswordResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "user"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._user)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_CreateWithPasswordResponse, rhs: Learningmotors_Pb_User_CreateWithPasswordResponse) -> Bool {
    if lhs._user != rhs._user {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_UpdateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "user"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeSingularMessageField(value: &self._user)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_UpdateRequest, rhs: Learningmotors_Pb_User_UpdateRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs._user != rhs._user {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_UpdateResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "user"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._user)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_UpdateResponse, rhs: Learningmotors_Pb_User_UpdateResponse) -> Bool {
    if lhs._user != rhs._user {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_DeleteRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeleteRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "ids"),
    3: .standard(proto: "perform_hard_delete"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeRepeatedStringField(value: &self.ids)
      case 3: try decoder.decodeSingularBoolField(value: &self.performHardDelete)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.ids.isEmpty {
      try visitor.visitRepeatedStringField(value: self.ids, fieldNumber: 2)
    }
    if self.performHardDelete != false {
      try visitor.visitSingularBoolField(value: self.performHardDelete, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_DeleteRequest, rhs: Learningmotors_Pb_User_DeleteRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.ids != rhs.ids {return false}
    if lhs.performHardDelete != rhs.performHardDelete {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_ActivateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ActivateRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeSingularStringField(value: &self.id)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_ActivateRequest, rhs: Learningmotors_Pb_User_ActivateRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_RegisterMarketplaceUserRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RegisterMarketplaceUserRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "user"),
    2: .standard(proto: "account_id"),
    3: .same(proto: "password"),
    4: .same(proto: "emr"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._user)
      case 2: try decoder.decodeSingularStringField(value: &self.accountID)
      case 3: try decoder.decodeSingularStringField(value: &self.password)
      case 4: try decoder.decodeSingularEnumField(value: &self.emr)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.accountID.isEmpty {
      try visitor.visitSingularStringField(value: self.accountID, fieldNumber: 2)
    }
    if !self.password.isEmpty {
      try visitor.visitSingularStringField(value: self.password, fieldNumber: 3)
    }
    if self.emr != .unknown {
      try visitor.visitSingularEnumField(value: self.emr, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_RegisterMarketplaceUserRequest, rhs: Learningmotors_Pb_User_RegisterMarketplaceUserRequest) -> Bool {
    if lhs._user != rhs._user {return false}
    if lhs.accountID != rhs.accountID {return false}
    if lhs.password != rhs.password {return false}
    if lhs.emr != rhs.emr {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_RegisterMarketplaceUserResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RegisterMarketplaceUserResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "user_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.userID)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_RegisterMarketplaceUserResponse, rhs: Learningmotors_Pb_User_RegisterMarketplaceUserResponse) -> Bool {
    if lhs.userID != rhs.userID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_SendGcpUsageMetricsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SendGcpUsageMetricsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_SendGcpUsageMetricsRequest, rhs: Learningmotors_Pb_User_SendGcpUsageMetricsRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Learningmotors_Pb_User_SendGcpUsageMetricsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SendGcpUsageMetricsResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Learningmotors_Pb_User_SendGcpUsageMetricsResponse, rhs: Learningmotors_Pb_User_SendGcpUsageMetricsResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
