// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: suki/pb/suki_server/v1/artifact.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated enum Suki_Pb_SukiServer_V1_RecommendationCategory: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unknownRecommendation // = 0
  case noteRecommendation // = 1
  case orderRecommendation // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unknownRecommendation
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknownRecommendation
    case 1: self = .noteRecommendation
    case 2: self = .orderRecommendation
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unknownRecommendation: return 0
    case .noteRecommendation: return 1
    case .orderRecommendation: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Suki_Pb_SukiServer_V1_RecommendationCategory] = [
    .unknownRecommendation,
    .noteRecommendation,
    .orderRecommendation,
  ]

}

nonisolated enum Suki_Pb_SukiServer_V1_RecommendationState: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case `default` // = 0
  case accept // = 1
  case reject // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .default
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .default
    case 1: self = .accept
    case 2: self = .reject
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .default: return 0
    case .accept: return 1
    case .reject: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Suki_Pb_SukiServer_V1_RecommendationState] = [
    .default,
    .accept,
    .reject,
  ]

}

nonisolated struct Suki_Pb_SukiServer_V1_ArtifactRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var request: Suki_Pb_SukiServer_V1_ArtifactRequest.OneOf_Request? = nil

  /// Get Artifact entities 
  var getOrdersRequest: Suki_Pb_SukiServer_V1_GetOrdersRequest {
    get {
      if case .getOrdersRequest(let v)? = request {return v}
      return Suki_Pb_SukiServer_V1_GetOrdersRequest()
    }
    set {request = .getOrdersRequest(newValue)}
  }

  /// Get Artifact Recommendations 
  var getOrderRecomRequest: Suki_Pb_SukiServer_V1_GetOrderRecommendationsRequest {
    get {
      if case .getOrderRecomRequest(let v)? = request {return v}
      return Suki_Pb_SukiServer_V1_GetOrderRecommendationsRequest()
    }
    set {request = .getOrderRecomRequest(newValue)}
  }

  var getNoteRecomRequest: Suki_Pb_SukiServer_V1_GetNoteRecommendationsRequest {
    get {
      if case .getNoteRecomRequest(let v)? = request {return v}
      return Suki_Pb_SukiServer_V1_GetNoteRecommendationsRequest()
    }
    set {request = .getNoteRecomRequest(newValue)}
  }

  /// User Action on Recommendation Requests 
  var updateOrderRecomStateRequest: Suki_Pb_SukiServer_V1_UpateOrderRecomStateRequest {
    get {
      if case .updateOrderRecomStateRequest(let v)? = request {return v}
      return Suki_Pb_SukiServer_V1_UpateOrderRecomStateRequest()
    }
    set {request = .updateOrderRecomStateRequest(newValue)}
  }

  /// request to update state of note recommendation
  var updateNoteRecomStateRequest: Suki_Pb_SukiServer_V1_UpateNoteRecomStateRequest {
    get {
      if case .updateNoteRecomStateRequest(let v)? = request {return v}
      return Suki_Pb_SukiServer_V1_UpateNoteRecomStateRequest()
    }
    set {request = .updateNoteRecomStateRequest(newValue)}
  }

  /// Mutate Orders Request 
  var deleteOrderRequest: Suki_Pb_SukiServer_V1_DeleteOrderRequest {
    get {
      if case .deleteOrderRequest(let v)? = request {return v}
      return Suki_Pb_SukiServer_V1_DeleteOrderRequest()
    }
    set {request = .deleteOrderRequest(newValue)}
  }

  /// request to update an existing order
  var updateOrderRequest: Suki_Pb_SukiServer_V1_UpdateOrderRequest {
    get {
      if case .updateOrderRequest(let v)? = request {return v}
      return Suki_Pb_SukiServer_V1_UpdateOrderRequest()
    }
    set {request = .updateOrderRequest(newValue)}
  }

  /// Note order sets 
  var getOrderSetsRequest: Suki_Pb_SukiServer_V1_GetOrderSetsRequest {
    get {
      if case .getOrderSetsRequest(let v)? = request {return v}
      return Suki_Pb_SukiServer_V1_GetOrderSetsRequest()
    }
    set {request = .getOrderSetsRequest(newValue)}
  }

  /// request to update applied order-set trees for a note
  var updateOrderSetsRequest: Suki_Pb_SukiServer_V1_UpdateOrderSetsRequest {
    get {
      if case .updateOrderSetsRequest(let v)? = request {return v}
      return Suki_Pb_SukiServer_V1_UpdateOrderSetsRequest()
    }
    set {request = .updateOrderSetsRequest(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Request: Equatable, Sendable {
    /// Get Artifact entities 
    case getOrdersRequest(Suki_Pb_SukiServer_V1_GetOrdersRequest)
    /// Get Artifact Recommendations 
    case getOrderRecomRequest(Suki_Pb_SukiServer_V1_GetOrderRecommendationsRequest)
    case getNoteRecomRequest(Suki_Pb_SukiServer_V1_GetNoteRecommendationsRequest)
    /// User Action on Recommendation Requests 
    case updateOrderRecomStateRequest(Suki_Pb_SukiServer_V1_UpateOrderRecomStateRequest)
    /// request to update state of note recommendation
    case updateNoteRecomStateRequest(Suki_Pb_SukiServer_V1_UpateNoteRecomStateRequest)
    /// Mutate Orders Request 
    case deleteOrderRequest(Suki_Pb_SukiServer_V1_DeleteOrderRequest)
    /// request to update an existing order
    case updateOrderRequest(Suki_Pb_SukiServer_V1_UpdateOrderRequest)
    /// Note order sets 
    case getOrderSetsRequest(Suki_Pb_SukiServer_V1_GetOrderSetsRequest)
    /// request to update applied order-set trees for a note
    case updateOrderSetsRequest(Suki_Pb_SukiServer_V1_UpdateOrderSetsRequest)

  }

  init() {}
}

/// request to get all the orders for an artifact or a note
nonisolated struct Suki_Pb_SukiServer_V1_GetOrdersRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// REQUIRED
  var encounterID: String = String()

  /// optional 
  var noteID: String = String()

  /// get orders filtered by submit_status
  var submitStatus: [Suki_Pb_Orders_Order.SubmitStatus] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// request to get applied order-set trees for a note
nonisolated struct Suki_Pb_SukiServer_V1_GetOrderSetsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Note id (orders.note_id).
  /// *required*
  var noteID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// request to update applied order-set trees for a note
nonisolated struct Suki_Pb_SukiServer_V1_UpdateOrderSetsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Note id (orders.note_id).
  /// *required*
  var noteID: String = String()

  /// Full desired list-of-lists body for this note.
  /// Each nested Order carries its own encounter_id/patient_id stamps.
  /// *required*
  var groups: [Suki_Pb_Orders_CompositionOrderSetGroup] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// request to get all order-recommendations for a note/artifact
nonisolated struct Suki_Pb_SukiServer_V1_GetOrderRecommendationsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// encounter-id of the order recommendations are generated
  var encounterID: String = String()

  /// note-id for which order recommendations are generated
  var noteID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// request to get all note-recommendations for a note
nonisolated struct Suki_Pb_SukiServer_V1_GetNoteRecommendationsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// note-id for which note recommendations are generated
  var noteID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// request to update state of order recommendation
nonisolated struct Suki_Pb_SukiServer_V1_UpateOrderRecomStateRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var updateRecommendationDetails: [Suki_Pb_SukiServer_V1_UpdatedRecommendationDetails] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// request to update state of note recommendation
nonisolated struct Suki_Pb_SukiServer_V1_UpateNoteRecomStateRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var updateRecommendationDetails: [Suki_Pb_SukiServer_V1_UpdatedRecommendationDetails] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// request to delete an order 
nonisolated struct Suki_Pb_SukiServer_V1_DeleteOrderRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// REQUIRED, id of the order to be deleted
  var id: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// request to update an existing order
nonisolated struct Suki_Pb_SukiServer_V1_UpdateOrderRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// order to be updated
  var order: Suki_Pb_Orders_Order {
    get {_order ?? Suki_Pb_Orders_Order()}
    set {_order = newValue}
  }
  /// Returns true if `order` has been explicitly set.
  var hasOrder: Bool {self._order != nil}
  /// Clears the value of `order`. Subsequent reads from it will return its default value.
  mutating func clearOrder() {self._order = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _order: Suki_Pb_Orders_Order? = nil
}

nonisolated struct Suki_Pb_SukiServer_V1_UpdatedRecommendationDetails: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///recommendation_id 
  var recommendationID: String = String()

  var recommendationState: Suki_Pb_SukiServer_V1_RecommendationState = .default

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Suki_Pb_SukiServer_V1_ArtifactResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var response: Suki_Pb_SukiServer_V1_ArtifactResponse.OneOf_Response? = nil

  /// Artifact entities 
  var getOrdersResponse: Suki_Pb_SukiServer_V1_GetOrdersResponse {
    get {
      if case .getOrdersResponse(let v)? = response {return v}
      return Suki_Pb_SukiServer_V1_GetOrdersResponse()
    }
    set {response = .getOrdersResponse(newValue)}
  }

  /// Artifact recommendations 
  var orderRecommendationResponse: Suki_Pb_SukiServer_V1_OrderRecommendationResponse {
    get {
      if case .orderRecommendationResponse(let v)? = response {return v}
      return Suki_Pb_SukiServer_V1_OrderRecommendationResponse()
    }
    set {response = .orderRecommendationResponse(newValue)}
  }

  /// Response for User Action on Recommendation 
  var orderResponse: Suki_Pb_SukiServer_V1_OrderResponse {
    get {
      if case .orderResponse(let v)? = response {return v}
      return Suki_Pb_SukiServer_V1_OrderResponse()
    }
    set {response = .orderResponse(newValue)}
  }

  /// Mutate Orders Response 
  var deleteOrderResponse: Suki_Pb_SukiServer_V1_DeleteOrderResponse {
    get {
      if case .deleteOrderResponse(let v)? = response {return v}
      return Suki_Pb_SukiServer_V1_DeleteOrderResponse()
    }
    set {response = .deleteOrderResponse(newValue)}
  }

  /// returns the updated order
  var updateOrderResponse: Suki_Pb_SukiServer_V1_UpdateOrderResponse {
    get {
      if case .updateOrderResponse(let v)? = response {return v}
      return Suki_Pb_SukiServer_V1_UpdateOrderResponse()
    }
    set {response = .updateOrderResponse(newValue)}
  }

  /// Note order sets 
  var getOrderSetsResponse: Suki_Pb_SukiServer_V1_GetOrderSetsResponse {
    get {
      if case .getOrderSetsResponse(let v)? = response {return v}
      return Suki_Pb_SukiServer_V1_GetOrderSetsResponse()
    }
    set {response = .getOrderSetsResponse(newValue)}
  }

  /// returns updated applied order-set trees for a note
  var updateOrderSetsResponse: Suki_Pb_SukiServer_V1_UpdateOrderSetsResponse {
    get {
      if case .updateOrderSetsResponse(let v)? = response {return v}
      return Suki_Pb_SukiServer_V1_UpdateOrderSetsResponse()
    }
    set {response = .updateOrderSetsResponse(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Response: Equatable, Sendable {
    /// Artifact entities 
    case getOrdersResponse(Suki_Pb_SukiServer_V1_GetOrdersResponse)
    /// Artifact recommendations 
    case orderRecommendationResponse(Suki_Pb_SukiServer_V1_OrderRecommendationResponse)
    /// Response for User Action on Recommendation 
    case orderResponse(Suki_Pb_SukiServer_V1_OrderResponse)
    /// Mutate Orders Response 
    case deleteOrderResponse(Suki_Pb_SukiServer_V1_DeleteOrderResponse)
    /// returns the updated order
    case updateOrderResponse(Suki_Pb_SukiServer_V1_UpdateOrderResponse)
    /// Note order sets 
    case getOrderSetsResponse(Suki_Pb_SukiServer_V1_GetOrderSetsResponse)
    /// returns updated applied order-set trees for a note
    case updateOrderSetsResponse(Suki_Pb_SukiServer_V1_UpdateOrderSetsResponse)

  }

  init() {}
}

/// TODO: send all types of orders using this order response.
nonisolated struct Suki_Pb_SukiServer_V1_GetOrdersResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var orders: [Suki_Pb_Orders_Order] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Applied note order-set trees (list-of-lists).
nonisolated struct Suki_Pb_SukiServer_V1_GetOrderSetsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var groups: [Suki_Pb_Orders_CompositionOrderSetGroup] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Echo of resulting note order-set trees after update.
nonisolated struct Suki_Pb_SukiServer_V1_UpdateOrderSetsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var groups: [Suki_Pb_Orders_CompositionOrderSetGroup] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Suki_Pb_SukiServer_V1_OrderRecommendationResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// OrderRecommendation and orders.Orders have the exact same structure and hence re-used here.
  var orderRecommendations: [Suki_Pb_Orders_Order] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Suki_Pb_SukiServer_V1_OrderResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// OrderRecommendation and orders.Orders have the exact same structure and hence re-used here.
  var orderRecommendations: [Suki_Pb_Orders_Order] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// response for updating an existing order
nonisolated struct Suki_Pb_SukiServer_V1_UpdateOrderResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// updated order
  var order: Suki_Pb_Orders_Order {
    get {_order ?? Suki_Pb_Orders_Order()}
    set {_order = newValue}
  }
  /// Returns true if `order` has been explicitly set.
  var hasOrder: Bool {self._order != nil}
  /// Clears the value of `order`. Subsequent reads from it will return its default value.
  mutating func clearOrder() {self._order = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _order: Suki_Pb_Orders_Order? = nil
}

/// Response for deleting a section from composition
nonisolated struct Suki_Pb_SukiServer_V1_DeleteOrderResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// id of the order that was supposed to deleted
  var id: String = String()

  var status: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "suki.pb.suki_server.v1"

nonisolated extension Suki_Pb_SukiServer_V1_RecommendationCategory: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNKNOWN_RECOMMENDATION\0\u{1}NOTE_RECOMMENDATION\0\u{1}ORDER_RECOMMENDATION\0")
}

nonisolated extension Suki_Pb_SukiServer_V1_RecommendationState: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DEFAULT\0\u{1}ACCEPT\0\u{1}REJECT\0")
}

nonisolated extension Suki_Pb_SukiServer_V1_ArtifactRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ArtifactRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}get_orders_request\0\u{4}\u{2}get_order_recom_request\0\u{3}get_note_recom_request\0\u{3}update_order_recom_state_request\0\u{3}update_note_recom_state_request\0\u{3}delete_order_request\0\u{3}update_order_request\0\u{3}get_order_sets_request\0\u{3}update_order_sets_request\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Suki_Pb_SukiServer_V1_GetOrdersRequest?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .getOrdersRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .getOrdersRequest(v)
        }
      }()
      case 3: try {
        var v: Suki_Pb_SukiServer_V1_GetOrderRecommendationsRequest?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .getOrderRecomRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .getOrderRecomRequest(v)
        }
      }()
      case 4: try {
        var v: Suki_Pb_SukiServer_V1_GetNoteRecommendationsRequest?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .getNoteRecomRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .getNoteRecomRequest(v)
        }
      }()
      case 5: try {
        var v: Suki_Pb_SukiServer_V1_UpateOrderRecomStateRequest?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .updateOrderRecomStateRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .updateOrderRecomStateRequest(v)
        }
      }()
      case 6: try {
        var v: Suki_Pb_SukiServer_V1_UpateNoteRecomStateRequest?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .updateNoteRecomStateRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .updateNoteRecomStateRequest(v)
        }
      }()
      case 7: try {
        var v: Suki_Pb_SukiServer_V1_DeleteOrderRequest?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .deleteOrderRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .deleteOrderRequest(v)
        }
      }()
      case 8: try {
        var v: Suki_Pb_SukiServer_V1_UpdateOrderRequest?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .updateOrderRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .updateOrderRequest(v)
        }
      }()
      case 9: try {
        var v: Suki_Pb_SukiServer_V1_GetOrderSetsRequest?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .getOrderSetsRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .getOrderSetsRequest(v)
        }
      }()
      case 10: try {
        var v: Suki_Pb_SukiServer_V1_UpdateOrderSetsRequest?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .updateOrderSetsRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .updateOrderSetsRequest(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.request {
    case .getOrdersRequest?: try {
      guard case .getOrdersRequest(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .getOrderRecomRequest?: try {
      guard case .getOrderRecomRequest(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .getNoteRecomRequest?: try {
      guard case .getNoteRecomRequest(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .updateOrderRecomStateRequest?: try {
      guard case .updateOrderRecomStateRequest(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .updateNoteRecomStateRequest?: try {
      guard case .updateNoteRecomStateRequest(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .deleteOrderRequest?: try {
      guard case .deleteOrderRequest(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .updateOrderRequest?: try {
      guard case .updateOrderRequest(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .getOrderSetsRequest?: try {
      guard case .getOrderSetsRequest(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .updateOrderSetsRequest?: try {
      guard case .updateOrderSetsRequest(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_ArtifactRequest, rhs: Suki_Pb_SukiServer_V1_ArtifactRequest) -> Bool {
    if lhs.request != rhs.request {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_GetOrdersRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetOrdersRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}encounter_id\0\u{3}note_id\0\u{3}submit_status\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.encounterID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.noteID) }()
      case 3: try { try decoder.decodeRepeatedEnumField(value: &self.submitStatus) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.encounterID.isEmpty {
      try visitor.visitSingularStringField(value: self.encounterID, fieldNumber: 1)
    }
    if !self.noteID.isEmpty {
      try visitor.visitSingularStringField(value: self.noteID, fieldNumber: 2)
    }
    if !self.submitStatus.isEmpty {
      try visitor.visitPackedEnumField(value: self.submitStatus, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_GetOrdersRequest, rhs: Suki_Pb_SukiServer_V1_GetOrdersRequest) -> Bool {
    if lhs.encounterID != rhs.encounterID {return false}
    if lhs.noteID != rhs.noteID {return false}
    if lhs.submitStatus != rhs.submitStatus {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_GetOrderSetsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetOrderSetsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}note_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.noteID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.noteID.isEmpty {
      try visitor.visitSingularStringField(value: self.noteID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_GetOrderSetsRequest, rhs: Suki_Pb_SukiServer_V1_GetOrderSetsRequest) -> Bool {
    if lhs.noteID != rhs.noteID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_UpdateOrderSetsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateOrderSetsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}note_id\0\u{1}groups\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.noteID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.groups) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.noteID.isEmpty {
      try visitor.visitSingularStringField(value: self.noteID, fieldNumber: 1)
    }
    if !self.groups.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.groups, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_UpdateOrderSetsRequest, rhs: Suki_Pb_SukiServer_V1_UpdateOrderSetsRequest) -> Bool {
    if lhs.noteID != rhs.noteID {return false}
    if lhs.groups != rhs.groups {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_GetOrderRecommendationsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetOrderRecommendationsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}encounter_id\0\u{3}note_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.encounterID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.noteID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.encounterID.isEmpty {
      try visitor.visitSingularStringField(value: self.encounterID, fieldNumber: 1)
    }
    if !self.noteID.isEmpty {
      try visitor.visitSingularStringField(value: self.noteID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_GetOrderRecommendationsRequest, rhs: Suki_Pb_SukiServer_V1_GetOrderRecommendationsRequest) -> Bool {
    if lhs.encounterID != rhs.encounterID {return false}
    if lhs.noteID != rhs.noteID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_GetNoteRecommendationsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetNoteRecommendationsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}note_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.noteID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.noteID.isEmpty {
      try visitor.visitSingularStringField(value: self.noteID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_GetNoteRecommendationsRequest, rhs: Suki_Pb_SukiServer_V1_GetNoteRecommendationsRequest) -> Bool {
    if lhs.noteID != rhs.noteID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_UpateOrderRecomStateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpateOrderRecomStateRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}update_recommendation_details\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.updateRecommendationDetails) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.updateRecommendationDetails.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.updateRecommendationDetails, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_UpateOrderRecomStateRequest, rhs: Suki_Pb_SukiServer_V1_UpateOrderRecomStateRequest) -> Bool {
    if lhs.updateRecommendationDetails != rhs.updateRecommendationDetails {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_UpateNoteRecomStateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpateNoteRecomStateRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}update_recommendation_details\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.updateRecommendationDetails) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.updateRecommendationDetails.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.updateRecommendationDetails, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_UpateNoteRecomStateRequest, rhs: Suki_Pb_SukiServer_V1_UpateNoteRecomStateRequest) -> Bool {
    if lhs.updateRecommendationDetails != rhs.updateRecommendationDetails {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_DeleteOrderRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeleteOrderRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_DeleteOrderRequest, rhs: Suki_Pb_SukiServer_V1_DeleteOrderRequest) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_UpdateOrderRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateOrderRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}order\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._order) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._order {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_UpdateOrderRequest, rhs: Suki_Pb_SukiServer_V1_UpdateOrderRequest) -> Bool {
    if lhs._order != rhs._order {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_UpdatedRecommendationDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdatedRecommendationDetails"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}recommendation_id\0\u{3}recommendation_state\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.recommendationID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.recommendationState) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.recommendationID.isEmpty {
      try visitor.visitSingularStringField(value: self.recommendationID, fieldNumber: 1)
    }
    if self.recommendationState != .default {
      try visitor.visitSingularEnumField(value: self.recommendationState, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_UpdatedRecommendationDetails, rhs: Suki_Pb_SukiServer_V1_UpdatedRecommendationDetails) -> Bool {
    if lhs.recommendationID != rhs.recommendationID {return false}
    if lhs.recommendationState != rhs.recommendationState {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_ArtifactResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ArtifactResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}get_orders_response\0\u{4}\u{3}order_recommendation_response\0\u{4}\u{3}order_response\0\u{3}delete_order_response\0\u{3}update_order_response\0\u{3}get_order_sets_response\0\u{3}update_order_sets_response\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Suki_Pb_SukiServer_V1_GetOrdersResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .getOrdersResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .getOrdersResponse(v)
        }
      }()
      case 4: try {
        var v: Suki_Pb_SukiServer_V1_OrderRecommendationResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .orderRecommendationResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .orderRecommendationResponse(v)
        }
      }()
      case 7: try {
        var v: Suki_Pb_SukiServer_V1_OrderResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .orderResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .orderResponse(v)
        }
      }()
      case 8: try {
        var v: Suki_Pb_SukiServer_V1_DeleteOrderResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .deleteOrderResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .deleteOrderResponse(v)
        }
      }()
      case 9: try {
        var v: Suki_Pb_SukiServer_V1_UpdateOrderResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .updateOrderResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .updateOrderResponse(v)
        }
      }()
      case 10: try {
        var v: Suki_Pb_SukiServer_V1_GetOrderSetsResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .getOrderSetsResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .getOrderSetsResponse(v)
        }
      }()
      case 11: try {
        var v: Suki_Pb_SukiServer_V1_UpdateOrderSetsResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .updateOrderSetsResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .updateOrderSetsResponse(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.response {
    case .getOrdersResponse?: try {
      guard case .getOrdersResponse(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .orderRecommendationResponse?: try {
      guard case .orderRecommendationResponse(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .orderResponse?: try {
      guard case .orderResponse(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .deleteOrderResponse?: try {
      guard case .deleteOrderResponse(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .updateOrderResponse?: try {
      guard case .updateOrderResponse(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .getOrderSetsResponse?: try {
      guard case .getOrderSetsResponse(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .updateOrderSetsResponse?: try {
      guard case .updateOrderSetsResponse(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_ArtifactResponse, rhs: Suki_Pb_SukiServer_V1_ArtifactResponse) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_GetOrdersResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetOrdersResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}orders\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.orders) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.orders.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.orders, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_GetOrdersResponse, rhs: Suki_Pb_SukiServer_V1_GetOrdersResponse) -> Bool {
    if lhs.orders != rhs.orders {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_GetOrderSetsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetOrderSetsResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}groups\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.groups) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.groups.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.groups, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_GetOrderSetsResponse, rhs: Suki_Pb_SukiServer_V1_GetOrderSetsResponse) -> Bool {
    if lhs.groups != rhs.groups {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_UpdateOrderSetsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateOrderSetsResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}groups\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.groups) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.groups.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.groups, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_UpdateOrderSetsResponse, rhs: Suki_Pb_SukiServer_V1_UpdateOrderSetsResponse) -> Bool {
    if lhs.groups != rhs.groups {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_OrderRecommendationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".OrderRecommendationResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}order_recommendations\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.orderRecommendations) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.orderRecommendations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.orderRecommendations, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_OrderRecommendationResponse, rhs: Suki_Pb_SukiServer_V1_OrderRecommendationResponse) -> Bool {
    if lhs.orderRecommendations != rhs.orderRecommendations {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_OrderResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".OrderResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}order_recommendations\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.orderRecommendations) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.orderRecommendations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.orderRecommendations, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_OrderResponse, rhs: Suki_Pb_SukiServer_V1_OrderResponse) -> Bool {
    if lhs.orderRecommendations != rhs.orderRecommendations {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_UpdateOrderResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateOrderResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}order\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._order) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._order {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_UpdateOrderResponse, rhs: Suki_Pb_SukiServer_V1_UpdateOrderResponse) -> Bool {
    if lhs._order != rhs._order {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_SukiServer_V1_DeleteOrderResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeleteOrderResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}status\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.status) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if self.status != false {
      try visitor.visitSingularBoolField(value: self.status, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_SukiServer_V1_DeleteOrderResponse, rhs: Suki_Pb_SukiServer_V1_DeleteOrderResponse) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
