// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: suki/pb/orders/lab_order.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Suki_Pb_Orders_LabOrderInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var suggestedLabOrderCode: Suki_Pb_Orders_LabOrderCode {
    get {_suggestedLabOrderCode ?? Suki_Pb_Orders_LabOrderCode()}
    set {_suggestedLabOrderCode = newValue}
  }
  /// Returns true if `suggestedLabOrderCode` has been explicitly set.
  var hasSuggestedLabOrderCode: Bool {self._suggestedLabOrderCode != nil}
  /// Clears the value of `suggestedLabOrderCode`. Subsequent reads from it will return its default value.
  mutating func clearSuggestedLabOrderCode() {self._suggestedLabOrderCode = nil}

  var facilityNote: String = String()

  var futureSubmitDate: String = String()

  var highPriority: Bool = false

  var providerNote: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _suggestedLabOrderCode: Suki_Pb_Orders_LabOrderCode? = nil
}

nonisolated struct Suki_Pb_Orders_LabOrderCode: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var codingSystem: Suki_Pb_Orders_LabOrderCode.CodingSystem = .loinc

  var code: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum CodingSystem: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case loinc // = 0

    /// EHR catalog order type id carried as a code
    case orderTypeID // = 1
    case UNRECOGNIZED(Int)

    init() {
      self = .loinc
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .loinc
      case 1: self = .orderTypeID
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .loinc: return 0
      case .orderTypeID: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Suki_Pb_Orders_LabOrderCode.CodingSystem] = [
      .loinc,
      .orderTypeID,
    ]

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "suki.pb.orders"

nonisolated extension Suki_Pb_Orders_LabOrderInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LabOrderInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}suggested_lab_order_code\0\u{3}facility_note\0\u{3}future_submit_date\0\u{3}high_priority\0\u{3}provider_note\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._suggestedLabOrderCode) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.facilityNote) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.futureSubmitDate) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.highPriority) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.providerNote) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try { if let v = self._suggestedLabOrderCode {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.facilityNote.isEmpty {
      try visitor.visitSingularStringField(value: self.facilityNote, fieldNumber: 3)
    }
    if !self.futureSubmitDate.isEmpty {
      try visitor.visitSingularStringField(value: self.futureSubmitDate, fieldNumber: 4)
    }
    if self.highPriority != false {
      try visitor.visitSingularBoolField(value: self.highPriority, fieldNumber: 5)
    }
    if !self.providerNote.isEmpty {
      try visitor.visitSingularStringField(value: self.providerNote, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Orders_LabOrderInfo, rhs: Suki_Pb_Orders_LabOrderInfo) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs._suggestedLabOrderCode != rhs._suggestedLabOrderCode {return false}
    if lhs.facilityNote != rhs.facilityNote {return false}
    if lhs.futureSubmitDate != rhs.futureSubmitDate {return false}
    if lhs.highPriority != rhs.highPriority {return false}
    if lhs.providerNote != rhs.providerNote {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Orders_LabOrderCode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LabOrderCode"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}coding_system\0\u{1}code\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.codingSystem) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.code) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.codingSystem != .loinc {
      try visitor.visitSingularEnumField(value: self.codingSystem, fieldNumber: 1)
    }
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Orders_LabOrderCode, rhs: Suki_Pb_Orders_LabOrderCode) -> Bool {
    if lhs.codingSystem != rhs.codingSystem {return false}
    if lhs.code != rhs.code {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Suki_Pb_Orders_LabOrderCode.CodingSystem: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0Loinc\0\u{1}ORDER_TYPE_ID\0")
}
