// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: suki/pb/emr/section_mapper/ms_emr_section_mapper.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A Mapping between a single Suki section and a single EMR section
struct Suki_Pb_Emr_SectionMapper_Mapping {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The Suki ID for the section as given by ms-sections
  /// *required*
  var sukiSectionID: String = String()

  /// The EMR Section
  /// *required*
  var emrSection: Suki_Pb_Emr_Section {
    get {return _emrSection ?? Suki_Pb_Emr_Section()}
    set {_emrSection = newValue}
  }
  /// Returns true if `emrSection` has been explicitly set.
  var hasEmrSection: Bool {return self._emrSection != nil}
  /// Clears the value of `emrSection`. Subsequent reads from it will return its default value.
  mutating func clearEmrSection() {self._emrSection = nil}

  /// Additional display names for the emr_section that may be encountered in old, non-suki created notes
  var aliases: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _emrSection: Suki_Pb_Emr_Section? = nil
}

/// Creates new section mapping(s)
struct Suki_Pb_Emr_SectionMapper_CreateRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the section map(s) to be created
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// List of organizational section mappings to create
  var mappings: [Suki_Pb_Emr_SectionMapper_Mapping] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

/// Deletes existing section mapping(s)
struct Suki_Pb_Emr_SectionMapper_DeleteRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the section map(s) to be deleted
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// List of the suki section ids whose mappings should be deleted
  var sukiSectionIds: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

/// Retrieves the section mappings for a given organization based on Scope.
struct Suki_Pb_Emr_SectionMapper_GetRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the section map to be retrieved
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// Filter that when provided will request the mappings for only the suki section ids provided
  var sukiSectionIds: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

/// Response containing the section mappings
struct Suki_Pb_Emr_SectionMapper_GetResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of organizational section mappings
  var mappings: [Suki_Pb_Emr_SectionMapper_Mapping] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Updates existing section mappings
struct Suki_Pb_Emr_SectionMapper_UpdateRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scope of the section map to be updated
  /// *required*
  var scope: Learningmotors_Pb_Scope_Scope {
    get {return _scope ?? Learningmotors_Pb_Scope_Scope()}
    set {_scope = newValue}
  }
  /// Returns true if `scope` has been explicitly set.
  var hasScope: Bool {return self._scope != nil}
  /// Clears the value of `scope`. Subsequent reads from it will return its default value.
  mutating func clearScope() {self._scope = nil}

  /// List of organizational section mappings to update
  var mappings: [Suki_Pb_Emr_SectionMapper_Mapping] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _scope: Learningmotors_Pb_Scope_Scope? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "suki.pb.emr.section_mapper"

extension Suki_Pb_Emr_SectionMapper_Mapping: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Mapping"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "suki_section_id"),
    2: .standard(proto: "emr_section"),
    3: .same(proto: "aliases"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.sukiSectionID)
      case 2: try decoder.decodeSingularMessageField(value: &self._emrSection)
      case 3: try decoder.decodeRepeatedStringField(value: &self.aliases)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sukiSectionID.isEmpty {
      try visitor.visitSingularStringField(value: self.sukiSectionID, fieldNumber: 1)
    }
    if let v = self._emrSection {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    if !self.aliases.isEmpty {
      try visitor.visitRepeatedStringField(value: self.aliases, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Emr_SectionMapper_Mapping, rhs: Suki_Pb_Emr_SectionMapper_Mapping) -> Bool {
    if lhs.sukiSectionID != rhs.sukiSectionID {return false}
    if lhs._emrSection != rhs._emrSection {return false}
    if lhs.aliases != rhs.aliases {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Suki_Pb_Emr_SectionMapper_CreateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "mappings"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.mappings)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.mappings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.mappings, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Emr_SectionMapper_CreateRequest, rhs: Suki_Pb_Emr_SectionMapper_CreateRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.mappings != rhs.mappings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Suki_Pb_Emr_SectionMapper_DeleteRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeleteRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .standard(proto: "suki_section_ids"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeRepeatedStringField(value: &self.sukiSectionIds)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.sukiSectionIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.sukiSectionIds, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Emr_SectionMapper_DeleteRequest, rhs: Suki_Pb_Emr_SectionMapper_DeleteRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.sukiSectionIds != rhs.sukiSectionIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Suki_Pb_Emr_SectionMapper_GetRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .standard(proto: "suki_section_ids"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeRepeatedStringField(value: &self.sukiSectionIds)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.sukiSectionIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.sukiSectionIds, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Emr_SectionMapper_GetRequest, rhs: Suki_Pb_Emr_SectionMapper_GetRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.sukiSectionIds != rhs.sukiSectionIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Suki_Pb_Emr_SectionMapper_GetResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "mappings"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedMessageField(value: &self.mappings)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mappings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.mappings, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Emr_SectionMapper_GetResponse, rhs: Suki_Pb_Emr_SectionMapper_GetResponse) -> Bool {
    if lhs.mappings != rhs.mappings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Suki_Pb_Emr_SectionMapper_UpdateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
    2: .same(proto: "mappings"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._scope)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.mappings)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._scope {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if !self.mappings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.mappings, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Suki_Pb_Emr_SectionMapper_UpdateRequest, rhs: Suki_Pb_Emr_SectionMapper_UpdateRequest) -> Bool {
    if lhs._scope != rhs._scope {return false}
    if lhs.mappings != rhs.mappings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
